### ISSUE TITLE
What is the correct way to test paginate outside of the FastApi route?

### ISSUE THREAD

**Issue by vadim-feskov** [uriyyo/fastapi-pagination#1003]
I want to separately test my piece of code that makes queries to the DB, including queries with pagination. The problem is that without explicitly specifying params, I get a "Use params or add_pagination" error. 
I've settled on explicitly throwing params from the test, but would like to know which way you think is correct?

**Comment by uriyyo** [comment]
Hi @vadim-feskov,

Best way will be to use `set_page` + explicit params passing:
```py
from fastapi_pagination import set_page, Page, Params
from fastapi_pagination.paginator import paginate

with set_page(Page[int]):
    page = paginate(
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        params=Params(
            page=2,
            size=5,
        ),
    )
```

**Comment by mahesh-hegde** [comment]
@uriyyo this is not very useful for testing.

Let's say I have a method

```
list_books() -> Page[Book]
```

It gets it's pagination parameter from FastAPI request's context. But when I am testing I don't have such context, and I can't modify list_books() method to take additional `Params`.

It would be nice if I can do something like:

```python
# Imaginary
page = list_books()
books_list: list[Book] = page.get_items(page=1, size=10)
```

**Comment by vadim-feskov** [comment]
Hey @uriyyo, sorry for disappearing. 
I added `params` attribute to my function with `default = None`, so i could pass parameters in the test, and at runtime they don't overwrite the real parameters added via add_pagination
```python
async def get_paginated_foo(
    self,
    params: AbstractParams | None = None,
) -> Page[Foo]:
    ...
    return await paginate(self.session, query, params)
```

But i agree with @mahesh-hegde, it would be really useful if it would be possible to add/override params for test specially

**Comment by uriyyo** [comment]
@vadim-feskov @mahesh-hegde 

I just released `0.12.16`  version that has `set_params` function that will allow you to set params value that will be used inside `paginate` call:
```py
from fastapi_pagination import Page, Params, paginate, set_page, set_params

set_page(Page[int])
set_params(Params(size=10, page=2))

page = paginate([*range(100)])

print(page.items)
```
```py
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```

**Comment by mahesh-hegde** [comment]
@uriyyo Nice. One question. Does the return value implement a context manager? can I do

```
with set_params(Params(size=10, page=2)):
  page = paginate(query)
  print(page)
```

And will params reset outside of this block? That would be great if possible.

Thanks

**Comment by uriyyo** [comment]
@mahesh-hegde Yup, both `set_params` and `set_page` can be used as context managers:
```py
from fastapi_pagination import Page, Params, paginate, set_page, set_params

with (
    set_page(Page[int]),
    set_params(Params(size=10, page=2)),
):
    page = paginate([*range(100)])

print(page.items)
```

> And will params reset outside of this block?
Yup, that's how it works

**Comment by mahesh-hegde** [comment]
Great. Thank you.

**Comment by uriyyo** [comment]
@vadim-feskov Can I close this issue?

**Comment by uriyyo** [comment]
Hi @vadim-feskov,

I am closing this issue, please reopen it in case you still have any issues.
