### ISSUE TITLE
Add Python 3.12 support

### ISSUE THREAD

**Issue by bike-picket** [uriyyo/fastapi-pagination#1013]
Please add support for Python 3.12. As I see, the library is not tested for Python 3.12, so I am not sure if the library will work correctly (`python-version: [ "3.8", "3.9", "3.10", "3.11" ]`): https://github.com/uriyyo/fastapi-pagination/blob/main/.github/workflows/test.yml#L18.

**Comment by uriyyo** [comment]
Hi @bike-picket 

New version `0.12.15` has been released, and now python 3.12 is officially supported

**Comment by bike-picket** [comment]
> Add python 3.12 official support #1023

Thank you a lot! Appreciate the quick update on this.
