### ISSUE TITLE
Does not work when model has unhashable columns

### ISSUE THREAD

**Issue by Julian-Sam** [uriyyo/fastapi-pagination#1024]
Here is an example, we use a json_field column in our Example table.

```
class Example(Base):
    __tablename__ = "example"

    id: Mapped[str] = mapped_column(
        primary_key=True,
        index=True,
    )

    json_field: Mapped[dict] = mapped_column(JSON, default=lambda: [])
```

Then if we try to paginate it as follows:

```
@router.get("/", response_model=Page[ExampleOut])
async def get_examples(
    db_session: AsyncSession,
):
    query = (
        select(Product).subquery()
    )
    return await paginate(
        db_session,
        query,
    )

```

I am getting an error:

`sqlalchemy.exc.InvalidRequestError: Can't apply uniqueness to row tuple containing value of type JSON(astext_type=Text()); this datatype produces non-hashable values`

Which is gotten from:
```
  File ".../fastapi_pagination/ext/sqlalchemy.py", line 130, in exec_pagination
    items = _maybe_unique(conn.execute(query), unique)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../fastapi_pagination/ext/sqlalchemy.py", line 76, in _maybe_unique
    return (result.unique() if unique else result).all()
```

Can we ignore applying uniqueness if we have unhashable columns? Or is there a better solution, or another workaround for this issue?

(Side note: I am using `.subquery()` because of this error if I don't use it:
`sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got <sqlalchemy.sql.selectable.Select object at 0x14c59dd90>. To create a FROM clause from a <class 'sqlalchemy.sql.selectable.Select'> object, use the .subquery() method. (Background on this error at: https://sqlalche.me/e/20/89ve)`)

**Comment by uriyyo** [comment]
Hi @Julian-Sam,

You need to use `unique=False`:
```py
@router.get("/", response_model=Page[ExampleOut])
async def get_examples(
    db_session: AsyncSession,
):
    query = (
        select(Product).subquery()
    )
    return await paginate(
        db_session,
        query,
       unique=False,
    )
```

**Comment by uriyyo** [comment]
No worries, thanks for your feedback!
