### ISSUE TITLE
How to remove or rename CustomizedPage... in schema

### ISSUE THREAD

**Issue by damilareisaac** [uriyyo/fastapi-pagination#1041]
I am not sure if this is a fastapi issue or the pagination. 

I have this CustomizedPage... for all of my schema documentation. Will like to rename or removed them.

<img width="528" alt="Screenshot 2024-02-22 103249" src="https://github.com/uriyyo/fastapi-pagination/assets/19874661/cad6f37e-b59e-4279-b77b-1403d827ff24">

**Comment by uriyyo** [comment]
Hi,

You can change the name using `cls_name` parameter:
```py
 Page = Page.with_custom_options(
    cls_name="Page",
    ... # your custom options
)
```

**Comment by damilareisaac** [comment]
Thank you, that only changed the CustomziedPage. I will love to change the whole name completely. 

e.g. CustomizedPage_UserResponse to just UserResponse.

**Comment by uriyyo** [comment]
Hi @damilareisaac,

The new way is actually will be to use `UseName` customizer:
```py
from fastapi_pagination.customization import CustomizedPage, UseName

IntPage = CustomizedPage[
    Page[int],
    UseName("IntPage"), 
]
```

Checkout docs - https://uriyyo-fastapi-pagination.netlify.app/tutorials_advanced/customization/

**Comment by uriyyo** [comment]
@damilareisaac I'm closing this issue. Please, reopen it in case this issue is still relevant.
