### ISSUE TITLE
0.12.20 breaks code that uses fastapi_pagination.ext.sqlalchemy.paginate_query

### ISSUE THREAD

**Issue by seaninmar** [uriyyo/fastapi-pagination#1092]
The removal of `fastapi_pagination.ext.sqlalchemy.paginate_query` from 0.12.20 (since 0.12.19) breaks the API for code that uses that function.

Please roll this change back for 0.12.21 and release a new 0.13.0 minor version with the change.

**Comment by uriyyo** [comment]
Sorry, my bad

**Comment by uriyyo** [comment]
Hi @seaninmar,

New vesion `0.12.21` has been released. Please, check if it fixed your issue.
