### ISSUE TITLE
Using add_pagination breaks the custom OpenAPI configuration.

### ISSUE THREAD

**Issue by mmzeynalli** [uriyyo/fastapi-pagination#1104]
So, in my project, I have a custom openAPI config:

```Python
def custom_openapi(app: Any) -> Any | Dict[str, Any]:
    """OpenApi settings"""
    if app.openapi_schema:
        return app.openapi_schema

    openapi_schema = get_openapi(
        title=settings.APP_TITLE,
        version=settings.API_VERSION,
        description=settings.APP_DESCRIPTION,
        routes=app.routes,
    )
    openapi_schema['components']['securitySchemes'] = {
        'Bearer Auth': {
            'type': 'http',
            'scheme': 'bearer',
            'in': 'header',
            'bearerFormat': 'JWT',
            'name': 'Authorization',
            'description': "Enter: **'&lt;JWT&gt;'**, where JWT is the access token",
        },
    }
    app.openapi_schema = openapi_schema

    return app.openapi_schema
```

Which worked all well until I added the `add_pagination(app)` line to the code. It does not matter if this function is before or after the custom_openapi call.

Before add_pagination was added:
<img width="654" alt="image" src="https://github.com/uriyyo/fastapi-pagination/assets/33568903/d0cc8ce3-a7da-4596-934a-7dd0df5ed767">

After add_pagination was added:
<img width="649" alt="image" src="https://github.com/uriyyo/fastapi-pagination/assets/33568903/d2851593-2f8e-48d4-aa51-a302005d71a2">

**Comment by uriyyo** [comment]
Hi @mmzeynalli,

Could you please put your openapi schema patch inside lifespan?
```

**Comment by mmzeynalli** [comment]
It works, but I would ask for a fix, as this is a workaround. Thanks though.

**Comment by uriyyo** [comment]
Hi @mmzeynalli,

I'm closing this issue, please reopen it in case if issue still appears on your side.
