### ISSUE TITLE
Add limit to CursorParams.size field

### ISSUE THREAD

**Issue by barsikus007** [uriyyo/fastapi-pagination#1116]
it would be great, if you add default limit to cursor-based pagination like in the Page one (and, probably, use same description):
```py
class CursorParams(BaseModel, AbstractParams):
    cursor: Optional[str] = Query(None, description="Cursor for the next page")
    size: int = Query(50, ge=0, le=100, description="Page size")

    str_cursor: ClassVar[bool] = True

    def to_raw_params(self) -> CursorRawParams:
        return CursorRawParams(
            cursor=decode_cursor(self.cursor, to_str=self.str_cursor),
            size=self.size,
        )

```

**Comment by uriyyo** [comment]
Hi @barsikus007,

Thanks for your suggestion and they totally make sense. 

Would you like to open PR with a fix? I would be happy if you can help me 😃

**Comment by barsikus007** [comment]
I thought that it is very small change but okay)

**Comment by uriyyo** [comment]
Hi @barsikus007,

New version has been released that includes your fix!
