### ISSUE TITLE
Links return wrong last page link

### ISSUE THREAD

**Issue by milost77** [uriyyo/fastapi-pagination#112]
It is always +1 of what it should be. If there is 1 page it returns page 2 as last, if 10 then 11, etc.

```   
    "total": 171,

    "page": 0,

    "size": 50,

    "links": {
        "first": "/airports/?q=international&col=name&orderby=state&page=0",
        "last": "/airports/?q=international&col=name&orderby=state&page=4",
        "self": "/airports/?q=international&col=name&orderby=state",
        "next": "/airports/?q=international&col=name&orderby=state&page=1",
        "prev": null
    }
```

**Comment by uriyyo** [comment]
Hi @milost77,
Thanks for submitting issue, it maybe related to #105 #103. I will take a closer look.

**Comment by milost77** [comment]
Thank you. It seems that this is wrong:
fastapi_pagination/links/default.py:24
```last={"page": ceil(total / size)},```

If I change it to:
```last={"page": round(total / size) if size < total else 0},```

Then it seems to return expected number of the last page. I will test it more though.

**Comment by uriyyo** [comment]
Hi @milost77,

This issue was resolved by #105 and #103.

New version `0.7.4` is released. Could you please verify that this issue is no longer present at new version?

**Comment by milost77** [comment]
Hi, I tested just now and works for all cases I tried, thank you!

**Comment by uriyyo** [comment]
Great, I will close this issue.

Thanks for opening this issue, I forgot to publish this fix🙂
