### ISSUE TITLE
[feat] support for odmantic

### ISSUE THREAD

**Issue by baggiponte** [uriyyo/fastapi-pagination#1128]
Ciao! Great lib 😊 I am a bit of a fan of @art049's [odmantic](https://github.com/art049/odmantic), an ODM for MongoDB. Do you think it could be supported? How complex that could be? I could help out a bit.

**Comment by uriyyo** [comment]
Hi @baggiponte,

New version `0.12.24` has been released. `odmantic` should be supported now

**Comment by baggiponte** [comment]
Amazing! Thanks 🤩 Will test it soon.
