### ISSUE TITLE
Unitest with pagination using Magicmock (mockey patching)

### ISSUE THREAD

**Issue by damilareisaac** [uriyyo/fastapi-pagination#1144]
I guess this is more of a question than a bug 
 I am trying to run unit test on pagination without connecting to the real database so using Magic Mock to fake database session and generating fake data with faker. 
The endpoint example

```
from fastapi import APIRouter, Depends, HTTPException

@router.get("/")
async def get_all_products(db: Session = Depends(get_db)) -> List[ProductResponse]:
    return db.query(Product).all()


class ProductResponse(BaseModel):
    id: float
    date_created: datetime | None = None
```

The following test cases passed for the endpoint above (without using pagination)

```
def test_get_all_products(mock_db: MagicMock):
    response = client.get("/")
    mock_db.query.all = fake_product_response
    assert response.status_code == 200
    assert isinstance(response.json(), list)
    assert len(fake_product_response) == len(response.json())
```

Since the database session in the main route is passed in through dependency injection. The dependencies is replaced using 

```
from unittest.mock import MagicMock
import pytest
from dependencies.database import get_db
from main import app
mock_session: MagicMock = MagicMock()

def override_get_db():
    try:
        yield mock_session
    finally:
        ...
@pytest.fixture
def mock_db():
    return mock_session
app.dependency_overrides[get_db] = override_get_db
```

When I replace this endpoint to use pagination. I am not able to correctly get the  sequence of calls of the `paginate` function, replacing the List response above with paginated response 
```
@router.get("/")
async def get_all_product(db: Session = Depends(get_db)) -> Page[ProductResponse]:
    return paginate(db, select(Product))
```

got the following error:

```
fastapi.exceptions.ResponseValidationError: 1 validation errors:
E                 {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': <coroutine object greenlet_spawn at 0x7f99368628a0>, 'url': 'https://errors.pydantic.dev/2.6/v/model_attributes_type'}
```
In my opinion, this error means that the right object was not replaced with the fake data.

> What is the sequence of actions that get called to have the response paginated such as the `db.get.all` above

> Or the better questions is how to use database dependencies override with paginate. 

Thank you in anticipation

**Comment by uriyyo** [comment]
Hi @damilareisaac,

I would recommend you mock `paginage` function. It would be much easier for you rather play-around with how to correctly mock `sqlachemy.Session`.

**Comment by damilareisaac** [comment]
Hi @uriyyo , 

can you please provide an example of how mocking paginate will work in this case? I have used the `spec Session`

 still no difference

**Comment by uriyyo** [comment]
@damilareisaac

Here is an example:
```py
mock_session.scalar.return_value = 100  # total values here
mock_session.execute.return_value.unique.return_value.all.return_value = [
    # mocked products here
]
```

**Comment by damilareisaac** [comment]
> @damilareisaac
> 
> Here is an example:
> 
> ```python
> mock_session.scalar.return_value = 100  # total values here
> mock_session.execute.return_value.unique.return_value.all.return_value = [
>     # mocked products here
> ]
> ```

Perfect the order is `execute -> unique -> all`
