### ISSUE TITLE
Document additional functionality (e.g. `resolve_params`, `set_params`)

### ISSUE THREAD

**Issue by widal001** [uriyyo/fastapi-pagination#1147]
@widal001 I would love it if you could help me with documentation.

I feel like there is a lot of functionality that is not covered in the documentation.

For instance, here is the functionality from https://github.com/uriyyo/fastapi-pagination/blob/main/fastapi_pagination/api.py that is not covered at all:
* resolve_params
* create_page
* set_params
* set_page
* set_items_transformer
* pagination_ctx

These are the first things that come to my mind, I am sure that there is more to cover. It will be also great to improve existing docs.

_Originally posted by @uriyyo in https://github.com/uriyyo/fastapi-pagination/issues/265#issuecomment-1962332096_

**Comment by widal001** [comment]
@uriyyo I created this to reference the work that I'll plan to do related to documentation. Feel free to assign this ticket to me and I'll create a PR that references this issue!

**Comment by uriyyo** [comment]
@widal001 Great, thank you so much!

**Comment by uriyyo** [comment]
@widal001 Hi, any updates? Are you still interested in this?

**Comment by widal001** [comment]
@uriyyo Hi yes! Thanks for the nudge. I just started this branch and made an [initial commit that added some TODOs](https://github.com/widal001/fastapi-pagination/blob/3ce378a4261e5c192b9d1a06beca0d9da8e6661f/fastapi_pagination/api.py#L66) where I think some docstrings would be helpful.

Beyond those docstrings, were you hoping to have those methods documented in the official docs as well? If so, is there a specific section of the docs where I should add examples of using those functions?

**Comment by uriyyo** [comment]
> Beyond those docstrings, were you hoping to have those methods documented in the official docs as well? If so, is there a specific section of the docs where I should add examples of using those functions?

That's a good question. I guess we can add another page to the `Tutorials - User Guide` section.

**Comment by uriyyo** [comment]
Hi @widal001,

I updated docs and cover all this functionality, I would be happy if you could review it and open PR with fixes.

Meanwhile, we can close this issue 🙌
