### ISSUE TITLE
Using SQLAlchemy

### ISSUE THREAD

**Issue by limzyishere** [uriyyo/fastapi-pagination#1162]
Hello! Simple question if you wouldn't mind answering. I was reading the documentation and it states.

For instance, if you use SQLAlchemy you can use paginate from fastapi_pagination.ext.sqlalchemy module. What are the  consequences of using paginate from fastapi_pagination instead? It will load all the data in memory before paginating it? is my understanding correct?

Thank you!

**Comment by hasansezertasan** [comment]
Every `paginate` function requires some configuration against related ORM/ODM. The `paginate` function from `fastapi_pagination` is not meant to be used with SQLAlchemy.

**Comment by uriyyo** [comment]
@limzyishere Sorry for long response. Do you still have a question or @hasansezertasan answered it?

**Comment by uriyyo** [comment]
@limzyishere I'm closing this issue. Please, reopen it in case you still have questions.
