### ISSUE TITLE
TypeError: get_body_field() got an unexpected keyword argument 'dependant' (FastAPI >=0.112.4)

### ISSUE THREAD

**Issue by espdev** [uriyyo/fastapi-pagination#1273]
Hello!

I just update FastAPI version from 0.112.2 to 0.112.4 and fastapi-pagination is broken.

```
Traceback (most recent call last):
...
  File ".../python3.11/site-packages/fastapi_pagination/api.py", line 390, in add_pagination
    _add_pagination(parent)
  File ".../python3.11/site-packages/fastapi_pagination/api.py", line 380, in _add_pagination
    _update_route(route)
  File ".../python3.11/site-packages/fastapi_pagination/api.py", line 364, in _update_route
    route.body_field = get_body_field(dependant=route.dependant, name=route.unique_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_body_field() got an unexpected keyword argument 'dependant'
```

I don't know what happened, but it certainly doesn't follow the semver rules. Either FastAPI broke the public API in the patch version, or fastapi-pagination uses a private API.

**Comment by espdev** [comment]
Sorry, it seems this is a duplicate of: https://github.com/uriyyo/fastapi-pagination/issues/1272

**Comment by espdev** [comment]
There is the PR that changes keyword-only argument from `dependant` to `flat_dependant`:
https://github.com/fastapi/fastapi/pull/12117

And these changes made it into the patch release 0.112.4. This broke semver convention, leading to this issue.

**Comment by m4rcelofs** [comment]
> I don't know what happened, but it certainly doesn't follow the semver rules. Either FastAPI broke the public API in the patch version, or fastapi-pagination uses a private API.

At the risk of sounding pedantic - FastAPI is at `0.y.z`, which semver considers "initial development", as in - no stable API yet and things may break at any time

**Comment by espdev** [comment]
@m4rcelofs we use the following dependency specification for fastAPI:

```
fastapi = '^0.112.0'
```

This means that the `poetry update` function will not update `y` version for `0.y.z` dependency, only `z`.
So we expect that the PATCH version (`z`) will not break backwards compatibility for `0.y.z` dependencies anyway.

**Comment by uriyyo** [comment]
Hi all,

New version `0.12.27` has been released, this issue should be fixed now
