### ISSUE TITLE
Extra payload object in Swagger request examples when using FastAPI Pagination (version 0.12.27)

### ISSUE THREAD

**Issue by mahyarnzi** [uriyyo/fastapi-pagination#1299]
Describe the bug When using FastAPI Pagination (version 0.12.27) with FastAPI (version 0.115.0) and Pydantic 2.x, the Swagger UI shows an extra object (e.g., payload) around the body schema in the request examples.

For example, when using:

```python
from fastapi_pagination import Page, paginate, add_pagination
app = FastAPI()

@app.post("/employee/info", response_model=Page[TotalExportEmployeeInfo])
async def employee_information(payload: EntryEmployeeInfo):
    ...
    return paginate(result)

add_pagination(app)
``` 
The generated request example in Swagger shows:

```
{
  "payload": {
    "PersonnelCode": "1212",
    "UpdateTime": "2024-09-23 08:00:00",
    "UserName": "nazari"
  }
}
``` 

However, the desired request example should be:

```
{
  "PersonnelCode": "1212",
  "UpdateTime": "2024-09-23 08:00:00",
  "UserName": "nazari"
}
``` 

To Reproduce Steps to reproduce the behavior:

1. Install FastAPI 0.115.0, fastapi-pagination 0.12.27, and Pydantic 2.x.
2. Define an endpoint using Page for pagination.
3. Open the Swagger UI and check the request body example in Swagger.

**Expected behavior** Swagger should show the body example without the extra payload object.
**Actual behavior** An extra wrapper object is shown in the body example.

**Proposed Solution** The issue lies in the `_bet_body_field` function call in the `api.py` file of fastapi-pagination (version 0.12.27). Specifically, the parameter `embed_body_fields` is set to `True` in the call of the `get_body_field` function. Setting it to `False` resolves the issue.

In api.py, the line:
```python
@no_type_check
def _bet_body_field(route: APIRoute) -> Optional[Any]:
    try:
        # starting from fastapi 0.113.0 get_body_field changed its signature
        return get_body_field(flat_dependant=route.dependant, name=route.unique_id, embed_body_fields=True)
    except TypeError:
        return get_body_field(dependant=route.dependant, name=route.unique_id)
``` 

should be changed to:

```python
@no_type_check
def _bet_body_field(route: APIRoute) -> Optional[Any]:
    try:
        # starting from fastapi 0.113.0 get_body_field changed its signature
        return get_body_field(flat_dependant=route.dependant, name=route.unique_id, embed_body_fields=False)
    except TypeError:
        return get_body_field(dependant=route.dependant, name=route.unique_id)
``` 

**Additional context**
- FastAPI version: 0.115.0
- fastapi-pagination version: 0.12.27
- Pydantic version: 2.9.2

**Labels:**
- bug
- pagination
- swagger-ui

**Comment by uriyyo** [comment]
Hi @mahyarnzi,

Thanks for such detailed explanation, I will try to fix it ASAP!

**Comment by uriyyo** [comment]
Hi @mahyarnzi,

New version `0.12.28` has been released, this issue should be fixed now.

**Comment by uriyyo** [comment]
Hi @mahyarnzi,

I'm closing this issue, please reopen if it still exists on your side
