### ISSUE TITLE
SQLAlchemy deprecation warning with 0.12.28

### ISSUE THREAD

**Issue by palfrey** [uriyyo/fastapi-pagination#1311]
Weren't seeing this with 0.12.27, only 0.12.28
`sqlalchemy.exc.SADeprecationWarning: The SelectBase.c and SelectBase.columns attributes are deprecated and will be removed in a future release; these attributes implicitly create a subquery that should be explicit.  Please call SelectBase.subquery() first in order to create a subquery, which then contains this attribute.  To access the columns that this SELECT object SELECTs from, use the SelectBase.selected_columns attribute. (deprecated since: 1.4)`

I suspect this is due to https://github.com/uriyyo/fastapi-pagination/blob/main/fastapi_pagination/ext/sqlalchemy.py#L79 / https://github.com/uriyyo/fastapi-pagination/pull/1281

**Comment by palfrey** [comment]
For anyone else hitting this, adding `"ignore::sqlalchemy.exc.SADeprecationWarning:fastapi_pagination.ext.sqlalchemy:79",` to your pyproject.toml ignores solves this for the moment.

**Comment by alex-goswag** [comment]
Also seeing the same 

requirements.txt
```
fastapi[all]==0.115.0
sqlalchemy==2.0.32
fastapi-pagination==0.12.28
```

**Comment by uriyyo** [comment]
Hi @alex-goswag @palfrey,

New version `0.12.29` has been released. Could you please check if issue still exists on your side?

**Comment by palfrey** [comment]
> Hi @alex-goswag @palfrey,
> 
> New version `0.12.29` has been released. Could you please check if issue still exists on your side?

No longer seeing the issue with 0.12.29

**Comment by uriyyo** [comment]
Great, thanks for fast response!

**Comment by palfrey** [comment]
Thanks for the fast fix!
