### ISSUE TITLE
Make the max page size configurable

### ISSUE THREAD

**Issue by rplevka** [uriyyo/fastapi-pagination#1345]
I noticed, the maximum allowed page size is capped to `100`. I noticed this is defined in the `default.py`. I am not quite sure whether this is being able to be overridden in any way, but I would really appreciate if I could set it to a custom value

**Comment by uriyyo** [comment]
Hi @rplevka,

Please, check docs - https://uriyyo-fastapi-pagination.netlify.app/customization/customizers/use_params_fields/

Let me know if you have more questions

**Comment by rplevka** [comment]
Oh no! Sorry for that and thanks! That's really useful.
