### ISSUE TITLE
_should_unwrap_scalars incorrectly returns True for CompoundSelect

### ISSUE THREAD

**Issue by fraser-langton** [uriyyo/fastapi-pagination#1358]
When using a CompoundSelect (from a union) in [fastapi_pagination.ext.sqlalchemy._should_unwrap_scalars](https://github.com/uriyyo/fastapi-pagination/blob/main/fastapi_pagination/ext/sqlalchemy.py#L84C5-L84C27) returns True as query.column_descriptions raises AttributeError

This was a particularly nasty bug for me to troubleshoot because the shape of the data was different I thought I had written the query wrong, the model wrong, or something else.

As an immediate fix I would perhaps suggest checking query is of type [Selectable](https://github.com/uriyyo/fastapi-pagination/blob/main/fastapi_pagination/ext/sqlalchemy.py#L80C1-L80C11) then at least it would fail explicitly instead of defaulting to some behaviour that isn't clear? To at least stop someone else in future being as confused as me.

**Comment by uriyyo** [comment]
Hi @fraser-langton,

Thanks for such a well-described issue!

**Comment by uriyyo** [comment]
Hi @fraser-langton,

New version `0.12.32` has been released, this issue should be fixed now.

**Comment by uriyyo** [comment]
Hi @fraser-langton,

Can I close the issue? Is everything okay on your side?

**Comment by fraser-langton** [comment]
@uriyyo yep thanks!
