### ISSUE TITLE
Dynamic fields get lost during page creation 

### ISSUE THREAD

**Issue by rafi-rr** [uriyyo/fastapi-pagination#1362]
Hi,

My SELECT has several dynamic fields that are added as part of the query.
They're not part of my entity's Pydantic model so I'm using `extra="allow"`
I also added `UseModelConfig(extra="allow")` but the fields are lost here:

```
def create_pydantic_model(model_cls: Type[TModel], /, **kwargs: Any) -> TModel:
    if IS_PYDANTIC_V2:
        return model_cls.model_validate(kwargs, from_attributes=True)  # type: ignore

    return model_cls(**kwargs)

```
https://github.com/uriyyo/fastapi-pagination/blob/4b902e3d567f41e5fec289af3626655c717521d1/fastapi_pagination/utils.py#L171

The values are correct in `kwargs` but are dropped afterwards.

Any thoughts on how to preserve them?
Thanks.

**Comment by rafi-rr** [comment]
@uriyyo If I use `result = model_cls.model_construct(**kwargs)`, it works.
I don't even need to set `UseModelConfig(extra="allow")` because of this.

**Comment by uriyyo** [comment]
Hi @rafi-rr,

Try to add transformer:
```py
    page = paginate(
        session,
        query,
        transformer=lambda items: [item._asdict() for item in items],
    )

```

**Comment by rafi-rr** [comment]
That did the trick. Thanks @uriyyo
