### ISSUE TITLE
Tortoise Requirement out of date

### ISSUE THREAD

**Issue by markmiscavage** [uriyyo/fastapi-pagination#1379]
`tortoise-orm = { version = ">=0.16.18,<0.22.0,!=0.21.0", optional = true }`

The tortoise <0.22.0 requirement is out of date as the latest Tortoise-orm version is currently 0.22.1. I've tested with my own project and a local build of fastapi-pagination and everything appears to work without issue. It would be nice to bump this requirement if all your tests pass.

**Comment by uriyyo** [comment]
Hi @markmiscavage,

New version `0.12.33` has been released, this issue should be fixed now.

**Comment by uriyyo** [comment]
Hi,
I'm closing this issue, please reopen it in case of more questions/issues
