### ISSUE TITLE
`exclusiveMinimum` causes problems with swagger editor and Azure API Management

### ISSUE THREAD

**Issue by Alexander-N** [uriyyo/fastapi-pagination#147]
The use of `gt` to constrain the query parameters causes the openapi spec validation to fail for example in swagger editor and Azure API Management: https://github.com/tiangolo/fastapi/issues/240, https://github.com/tiangolo/fastapi/issues/3541
As workaround `ge` could be used instead, e.g.
```python
class Page(BasePage[T], Generic[T]):
    page: conint(ge=1)  # type: ignore
    size: conint(ge=1)  # type: ignore
```
instead of
```python
class Page(BasePage[T], Generic[T]):
    page: conint(gt=0)  # type: ignore
    size: conint(gt=0)  # type: ignore
```

**Comment by uriyyo** [comment]
@Alexander-N Could you please open PR with fix?
