### ISSUE TITLE
Page size as paginate() argument

### ISSUE THREAD

**Issue by zdytch** [uriyyo/fastapi-pagination#155]
The idea is to set page size in paginate() function. Maybe as an element of params.
So we could get this value from router argument or use some default size.

Something like this:
```
@router.get('', response_model=Page[ItemList])
async def get_item_list(page_size: int = 20):
    return paginate(items, page_size)
```

**Comment by zdytch** [comment]
@uriyyo 
Setting page size on client side is a common practice. Just a couple of screenshots from google images:
https://jochen.kirstaetter.name/content/images/2019/01/telerik_radgrid_custom_pagesize.png
https://user-images.githubusercontent.com/34887212/80689034-067cea80-8acd-11ea-8c8d-48cca138779c.png

For example, DRF allows client to send page_size as a query param:
https://www.django-rest-framework.org/api-guide/pagination/

However, I'm not sure, if `paginate()` function is the best place to set this parameter. Maybe better approach exists.

**Comment by uriyyo** [comment]
You can do it by passing `size` parameter in case of `Page` or `limit` parameter in case of `LimitOffsetPage`.

For instance:
```
@app.get('/users', response_model=Page[User])
async def get_users():
    return paginate(users)
```

```
curl http://localhost:8000/users?size=100
```

**Comment by zdytch** [comment]
@uriyyo
Hah, sorry for silly question!

**Comment by uriyyo** [comment]
No worries)
