### ISSUE TITLE
Bump sqlalchemy to 1.4

### ISSUE THREAD

**Issue by kigawas** [uriyyo/fastapi-pagination#160]
As mentioned in #159

**Comment by uriyyo** [comment]
@kigawas Thanks for suggestion. I think for this moment we can set minimal version of sqlalchemy to `1.3` so people who use old version of `sqlalchemy` can still use it and it want be required to them bump version of sqlalchemy to `1.4`.

What is your opinion regarding that&

**Comment by kigawas** [comment]
You can still use legacy APIs in sqlalchemy 1.4 so the difference is not that big.
I think to bump it in the next beta version (0.9?) is better.

**Comment by uriyyo** [comment]
Thanks makes sense, thanks for your opinion.
