### ISSUE TITLE
[Question] Any plan for integration with piccolo

### ISSUE THREAD

**Issue by satishdash** [uriyyo/fastapi-pagination#166]
Hi @uriyyo thanks for all the hardwork that has been put into this project. Would you plan on an integration with piccolo-orm (https://piccolo-orm.com/) in the coming days. We use piccolo for simplicity in its migrations and usage like django but with async capabilities.
If you get sometime to look over piccolo please do suggest any ideas you'd get on paginating a piccolo queryset with fast api.

**Comment by uriyyo** [comment]
Hi @satishdash,
I will take a closer look as soon as possible.

**Comment by uriyyo** [comment]
`piccolo` integration available at version `0.8.3`

**Comment by satishdash** [comment]
thanks a lot @uriyyo . the example is also clean. it is based on limit offset pagination. can it be extended to cursor based pagination too.?

**Comment by uriyyo** [comment]
It can be used with both. For cursor purposes you can use `fastapi_pagination.Page` class.
