### ISSUE TITLE
How to use paginate with sqlalchemy new query syntax

### ISSUE THREAD

**Issue by rafa761** [uriyyo/fastapi-pagination#191]
Hi

I'm trying to migrate to Sqlalchemy 1.4.23 and activate the new query syntax. But can't figure out how to use paginate function with it.

fastapi-pagination==0.8.3

```
from sqlalchemy.future import select
from models import UserModel


class User:
    def _init__(self, db_session):
        self.db_session = session

    def get_users():
        return select(UserModel)
```

The endpoint looks like this:

```
from fastapi_pagination.ext.sqlalchemy import paginate
from fastapi_pagination import Page, Params

@router.get('/get-users')
def get_users(self, 
                       page_schema: PaginationParams = Depends(),
                       db_session: Session = Depends(get_request_db)) -> Page[UserSchema]:
    users = User(db_session).get_users()

    return paginate(users, page_schema)
```

I'm getting this error:

![image](https://user-images.githubusercontent.com/41598843/132065495-f6d1ba5c-3140-43cc-bd54-23b5ad773c3e.png)

Also tried:

```
from sqlalchemy.future import select
from models import UserModel


class User:
    def _init__(self, db_session):
        self.db_session = session

    def get_users():
        return self.db_session.execute(select(UserModel))
```

but got this:

![image](https://user-images.githubusercontent.com/41598843/132065875-a33db008-c0ec-4805-8303-29c3b25df015.png)

**Comment by uriyyo** [comment]
Hi @rafa761,

Currently `fastapi-pagination` does not support `sqlalchemy` `1.14` version.
I am planing to include support at version `0.9.0`.

**Comment by uriyyo** [comment]
It related to #160

**Comment by rafa761** [comment]
ok, thank you for your effort on the project @uriyyo

**Comment by ToGoBananas** [comment]
@uriyyo hi, sorry to bother you but, do you have any ETA on the `0.9.0` version?

**Comment by uriyyo** [comment]
Hi @ToGoBananas,

I plaining to release new version during this week

**Comment by uriyyo** [comment]
Hi @ToGoBananas,
Version `0.9.0` has been released.
