### ISSUE TITLE
Outdated link in docs/index.md

### ISSUE THREAD

**Issue by itsuchur** [uriyyo/fastapi-pagination#195]
Greetings

Link to OpenAPI [here](https://github.com/uriyyo/fastapi-pagination/blob/main/docs/index.md) leads to https://github.com/uriyyo/fastapi-pagination/blob/main/images/openapi_example.png which doesn't exist. 

The correct link would be [this one](https://github.com/uriyyo/fastapi-pagination/blob/main/docs/images/openapi_example.png).

**Comment by uriyyo** [comment]
Yup, that a bug. Thanks for pointing on this.
