### ISSUE TITLE
Tortoise ORM extension

### ISSUE THREAD

**Issue by mrcartoonster** [uriyyo/fastapi-pagination#2]
Will you make a [Tortoise ORM](https://tortoise-orm.readthedocs.io/en/latest/) extension?

**Comment by uriyyo** [comment]
Hi, @mrcartoonster 

Definitely yes!
Tortoise is the next thing which I want to integrate with `fastapi-pagination`

**Comment by mrcartoonster** [comment]
Thank you! This is an AMAZING FastAPI extension.

**Comment by uriyyo** [comment]
I have implemented Tortoise ORM integration and it is available under `0.4.1` version.

To install `fastapi-pagination` with `Tortoise` integration please run
```sh
pip install -U fastapi-pagination[tortoise]
```

There is an example of how to integrate `fastapi-pagination` and `Tortoise`:
https://github.com/uriyyo/fastapi-pagination/blob/493531f89fcc9b8aa441f220880b510efd35f310/examples/pagination_tortoise.py#L1-L65

In case of any questions or issues feel free to reopen this issue.

**Comment by mrcartoonster** [comment]
Cool! I'll let you know if I run into any issues. I'll try it out by the end of today.
