### ISSUE TITLE
SQLModel integration

### ISSUE THREAD

**Issue by hacen-ai** [uriyyo/fastapi-pagination#201]
Hello, Do you have any plane to integrate tiangolo orm [SQLModel](https://github.com/tiangolo/sqlmodel) . If yes have you any ETA.

THanks for the great work.

**Comment by uriyyo** [comment]
Hi @hacen-ai,

Yup, I am planning to do it in the next release.

My ETA - one week.

**Comment by uriyyo** [comment]
Hi @hacen-ai,
Version 0.9.0 has been released.

**Comment by hacen-ai** [comment]
You are doing great job man.
Thank you for your work
