### ISSUE TITLE
add previous and next page which is available or not

### ISSUE THREAD

**Issue by sakthiRathinam** [uriyyo/fastapi-pagination#217]

**Comment by uriyyo** [comment]
In case if `prev` or `next` page is not available you will receive `None` as a value.

**Comment by sakthiRathinam** [comment]
but  im nt getting anything like prev or next

**Comment by sakthiRathinam** [comment]
@clinto_router.get('/paginateMedicines', response_model=Page[GET_Medicine])
async def paginate_mediciens(request: Request) -> any:
    medicines = await paginate(Medicine.all())

im using fastapi and tortoise-orm
