### ISSUE TITLE
Problem with sqlalchemy .

### ISSUE THREAD

**Issue by ScrimForever** [uriyyo/fastapi-pagination#218]
async def search_offertypes(order: bool = False, parameter: OffertypeList = Depends(),
                            db: Session = Depends(get_db)) -> Any:
    return paginate(db.query(OfferType))

output:

TypeError: object of type 'Query' has no len()

**Comment by uriyyo** [comment]
How route registration looks like?

**Comment by uriyyo** [comment]
I cann't see how `search_offertypes` is registred at `offer_router`

**Comment by ScrimForever** [comment]
import time
from fastapi import APIRouter, Depends
from typing import Any, List
from sqlalchemy.orm import Session
from offertype.core.utils import get_db
from offertype.models import OfferType
from fastapi.responses import JSONResponse
from offertype.schemas import OffertypeCreate, OffertypeList, OffertypeUpdate
from fastapi.requests import Request
from fastapi.exception_handlers import HTTPException
from fastapi_pagination.ext.sqlalchemy import paginate

offer_router = APIRouter()


@offer_router.post("")
async def create_offertype(offertype: OffertypeCreate, request: Request, db: Session = Depends(get_db)):

    try:
        offer = OfferType(**offertype.dict())
        offer.dt_create = time.ctime()
        db.add(offer)
        db.commit()
        db.refresh(offer)
        return offer
    except Exception as e:
        print(e)
        return JSONResponse(status_code=403, content={'Error': 'Não foi possível cadastrar a offertype'})


@offer_router.post("/teste/")
def search_offertypes(db: Session = Depends(get_db)) -> Any:
    return paginate(db.query(OfferType))

**Comment by uriyyo** [comment]
Try update code to (bassically you should set `response_model`):
```py
from fastapi_pagination import Page

@offer_router.get("/teste/", response_model=Page[Any])
def search_offertypes(db: Session = Depends(get_db)) -> Any:
    return paginate(db.query(OfferType))
```

**Comment by ScrimForever** [comment]
I i use any Pydantic models inside Page, this happen

**Comment by uriyyo** [comment]
No problem, happy you that you resolve your issue)
