### ISSUE TITLE
Fix the buy a coffee link

### ISSUE THREAD

**Issue by ets** [uriyyo/fastapi-pagination#230]
Appreciate today's update.  Tried to buy you a coffee but kept getting denied by Paypal & error message wasn't helpful.  Maybe look at Patreon or a Nano wallet?

**Comment by uriyyo** [comment]
Hi @ets,

I really appreciate it, but for me is enough that people are using my libraries. It's always a big pleasure to receive messages like this.

But anyway I replaced `buy me a coffee` with `patreon`. Here is a link to `patreon` - https://patreon.com/uriyyo
