### ISSUE TITLE
How to override the pagination page format

### ISSUE THREAD

**Issue by AntonGsv** [uriyyo/fastapi-pagination#248]
Default format:
```
{
  "items": [
    ...
  ],
  "total": 344,
  "page": 1,
  "size": 50
}
```
The format I wish to receive:
```
{
  "items": [
    ...
  ],
"pagination": {
        "total": 344,
        "page_number": 1,
        "last_page_number": 7,
        "size": 50,
    }
}
```
Can you please tell me how to get the desired response format?

**Comment by uriyyo** [comment]
Hi @AntonGsv,

You can implement custom `Page` type, smth like this:
```py
from typing import Generic, TypeVar, Sequence, Type, ClassVar

from math import ceil
from pydantic import BaseModel

from fastapi_pagination import Params
from fastapi_pagination.bases import AbstractParams, AbstractPage

T = TypeVar("T")


class Pagination(BaseModel):
    total: int
    page_number: int
    last_page_number: int
    size: int


class CustomPage(AbstractPage[T], Generic[T]):
    items: Sequence[T]
    pagination: Pagination

    __params_type__: ClassVar[Type[AbstractParams]] = Params

    @classmethod
    def create(
            cls: Type['CustomPage'],
            items: Sequence[T],
            total: int,
            params: AbstractParams,
    ) -> 'CustomPage':
        if not isinstance(params, Params):
            raise ValueError

        return cls(
            items=items,
            pagination=Pagination(
                total=total,
                page_number=params.page,
                size=params.size,
                last_page_number=ceil(total / params.size) if total > 0 else 1,
            ),
        )
```

**Comment by Tirth27** [comment]
Hi @AntonGsv 

> Hi @AntonGsv,
> 
> You can implement custom `Page` type, smth like this:
> 
> ```python
> from typing import Generic, TypeVar, Sequence, Type, ClassVar
> 
> from math import ceil
> from pydantic import BaseModel
> 
> from fastapi_pagination import Params
> from fastapi_pagination.bases import AbstractParams, AbstractPage
> 
> T = TypeVar("T")
> 
> 
> class Pagination(BaseModel):
>     total: int
>     page_number: int
>     last_page_number: int
>     size: int
> 
> 
> class CustomPage(AbstractPage[T], Generic[T]):
>     items: Sequence[T]
>     pagination: Pagination
> 
>     __params_type__: ClassVar[Type[AbstractParams]] = Params
> 
>     @classmethod
>     def create(
>             cls: Type['CustomPage'],
>             items: Sequence[T],
>             total: int,
>             params: AbstractParams,
>     ) -> 'CustomPage':
>         if not isinstance(params, Params):
>             raise ValueError
> 
>         return cls(
>             items=items,
>             pagination=Pagination(
>                 total=total,
>                 page_number=params.page,
>                 size=params.size,
>                 last_page_number=ceil(total / params.size) if total > 0 else 1,
>             ),
>         )
> ```

I want to customise the paginated response to following format:

```json
{
 "detail": {
    "something0": "string",
    "something1": "string",
    "something2": "string",
    "something3": "string"
     }
"items": [
  {
    ...
    }
  ],
"total": 0,
"page": 1,
"size": 1
}
```

When I used the snippet that you have provided it gives me `AttributeError`
`AttributeError: 'dict' object has no attribute 'to_raw_params'`

and the `detail` is something that I am appending to the query result. So how should I use that with `paginate`?

``` python
@router.post('/all', response_model=CustomPage[TableSchema])
async def get_list(request: Request, db: Session = Depends(get_db)):

    data = await db_query.query_all_rows(db, table_obj)

    custom = {}
    custom["detail"] = {
    "something0": "string",
    "something1": "string",
    "something2": "string",
    "something3": "string"
     }

    return paginate(data)
```

How should I used the `custom["detail"]` dict with `paginate(data)` to get something related to above response JSON.

**Comment by Tirth27** [comment]
Hi @uriyyo 

> Hi @AntonGsv,
> 
> You can implement custom `Page` type, smth like this:
> 
> ```python
> from typing import Generic, TypeVar, Sequence, Type, ClassVar
> 
> from math import ceil
> from pydantic import BaseModel
> 
> from fastapi_pagination import Params
> from fastapi_pagination.bases import AbstractParams, AbstractPage
> 
> T = TypeVar("T")
> 
> 
> class Pagination(BaseModel):
>     total: int
>     page_number: int
>     last_page_number: int
>     size: int
> 
> 
> class CustomPage(AbstractPage[T], Generic[T]):
>     items: Sequence[T]
>     pagination: Pagination
> 
>     __params_type__: ClassVar[Type[AbstractParams]] = Params
> 
>     @classmethod
>     def create(
>             cls: Type['CustomPage'],
>             items: Sequence[T],
>             total: int,
>             params: AbstractParams,
>     ) -> 'CustomPage':
>         if not isinstance(params, Params):
>             raise ValueError
> 
>         return cls(
>             items=items,
>             pagination=Pagination(
>                 total=total,
>                 page_number=params.page,
>                 size=params.size,
>                 last_page_number=ceil(total / params.size) if total > 0 else 1,
>             ),
>         )
> ```

I want to customise the paginated response to the following format:

```json
{
 "detail": {
    "something0": "string",
    "something1": "string",
    "something2": "string",
    "something3": "string"
     }
"items": [
  {
    ...
    }
  ],
"total": 0,
"page": 1,
"size": 1
}
```

When I used the snippet that you have provided it gives me `AttributeError`
`AttributeError: 'dict' object has no attribute 'to_raw_params'`

and the `detail` is something that I am appending to the query result. So how should I use that with `paginate`?

``` python
@router.post('/all', response_model=CustomPage[TableSchema])
async def get_list(request: Request, db: Session = Depends(get_db)):

    data = await db_query.query_all_rows(db, table_obj)

    custom = {}
    custom["detail"] = {
    "something0": "string",
    "something1": "string",
    "something2": "string",
    "something3": "string"
     }

    return paginate(data)
```

How should I use the `custom["detail"]` dict with `paginate(data)` to get something related to the above response JSON?
