### ISSUE TITLE
How to make external api call on paginated data

### ISSUE THREAD

**Issue by tiru1930** [uriyyo/fastapi-pagination#251]
I have fastapi service which is using fastapi-pagination, now it the service returns paginated response , Now i want for each page i need to make external api call to get some metadata and fill the response under the same api call , is this possible?

**Comment by uriyyo** [comment]
Hi @tiru1930,

Could you please provide minimal example so I can understand what you need.

**Comment by tiru1930** [comment]
Hi

It's fixed ,please close the ticket,  I have just made api call  to get
extran info on paginated items.
