### ISSUE TITLE
Query Specific Column only

### ISSUE THREAD

**Issue by Tirth27** [uriyyo/fastapi-pagination#256]
Hi There, 

Currently, the `fastapi-pagination` library returns all the columns in a table.

But rather than getting all the column from the table, can we specify only required columns? as I have table with more than 50 columns. So, I wanted to filter only required columns from the table using the query parameter from the API endpoint. Similar to [`q` in the fast api documentation. NOTE: Try Opening Link in Google Chrome, Will highlight the copied text](https://fastapi.tiangolo.com/ja/tutorial/dependencies/classes-as-dependencies/#:~:text=An%20optional%20q%20query%20parameter%20that%20is%20a%20str.)

Without using `fastapi-pagination` if I try the below code it will return response which will only contain `p_key`, `name` and `email` column name from the `SQLAlchemy_TABLE_OBJECT `. 
``` python
@router.post('/user/all', response_model=Users, response_model_exclude_none=True)
async def get_zone_code_list(request: Request, db: Session = Depends(get_db)):

    table_name = SQLAlchemy_TABLE_OBJECT
    data = db.query(table_name).\
        options(load_only("p_key", 'name', 'email')).\ #Return only Specific Column from the table
        order_by(table_name.p_key)

    return data

```

But when I try the same with `fastapi-pagination` it does not consider `options()` and return all the columns in the table. 

``` python
@router.post('/user/all', response_model=Page[Users], response_model_exclude_none=True)
async def get_zone_code_list(request: Request, db: Session = Depends(get_db)):

    table_name = SQLAlchemy_TABLE_OBJECT
    data = db.query(table_name).\
        options(load_only("p_key", 'name', 'email')).\
        order_by(table_name.p_key)

    return paginate(data)

```

**Also, what would be the best way to return only specific column from the table using the `fastapi-pagination` if not the method I mentioned above.**

**Comment by uriyyo** [comment]
Hi @Tirth27,

As an option, you can define a model with a custom `root_validator` that will convert objects into mapping and will include only loaded columns. Example:
```py
from pydantic import BaseModel
from pydantic.utils import GetterDict

class UserOutModel(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    email: Optional[str] = None

    @root_validator(skip_on_failure=True, pre=True)
    def __root_validator__(cls, values: Mapping[str, Any]) -> Mapping[str, Any]:
        if isinstance(values, GetterDict):
            return vars(values._obj)

        return values

    class Config:
        orm_mode = True


@app.get("/users/all", response_model=Page[UserOutModel], response_model_exclude_none=True)
def get_users(
    db: Session = Depends(get_db),
    columns: List[Literal["id", "name", "email"]] = Query(...),
) -> Any:
    return paginate(db.query(User).options(load_only(*columns)))
```

**Comment by Tirth27** [comment]
Amazing @uriyyo 😃, Thank you.

Currently, the `columns` field is compulsory in the Query parameter. I try to make it Optional so that if I do not select any value from the `columns` it will give me all the columns (by default). But was not able to configure, do you have any thoughts/suggestion on that?

Also, I have a table with more than 50 columns. And if I used the method you mention I have to manually create Pydantic Model `class UserOutModel(BaseModel):` for each 50 columns. Plus, I will have to include them in the `columns` (i.e. in `columns: List[Literal["id", "name", "email"]]`). 

I that case what would be the best way to approach? and I have many table which has more than 20 columns. In that case defining a Pydantic Model and again the query parameter will not be an appropriate way?

Thank you for the help :)

**Comment by uriyyo** [comment]
@Tirth27 you can create function that will extract field names from your pydantic model.

For instance:
```py
from typing import TYPE_CHECKING, get_args


def get_field_type(model: Type[BaseModel]) -> Any:
    return Literal[tuple(model.__fields__)]  # type: ignore


if TYPE_CHECKING:
    UserField = str
else:
    UserField = get_field_type(UserOutModel)


@app.get("/users/all", response_model=Page[UserOutModel], response_model_exclude_none=True)
def get_users(
    db: Session = Depends(get_db),
    columns: Optional[List[UserField]] = Query(None),
) -> Any:
    if columns is None:
        columns = get_args(UserField)

    return paginate(db.query(User).options(load_only(*columns)))
```

**Comment by uriyyo** [comment]
I will close this issue, in case if you have more questions please reopen this issue.
