### ISSUE TITLE
What this code?

### ISSUE THREAD

**Issue by david-shiko** [uriyyo/fastapi-pagination#269]
Please, provide a demo in readme.md or post a picture at least :)

**Comment by uriyyo** [comment]
@david-shiko Could you please provide more context? It's not clear to me what should be added.

**Comment by david-shiko** [comment]
I mean what this code intended for
Examples:
https://github.com/marirs/fastapi-boilerplate#fastapi-biolerplate
https://github.com/utmhikari/start-fastapi#start-fastapi
https://github.com/python-telegram-bot/python-telegram-bot/tree/v14#readme

**Comment by uriyyo** [comment]
I see, will add general information to `README.md`. Thanks for the issue.

**Comment by david-shiko** [comment]
Thanks but your example show **how** to use a repo but does not answer **why** to use. This's required for these are doesn't know what is _pagination_ in the context of Fastapi (like me)

**Comment by uriyyo** [comment]
@david-shiko I will add this information in scope of #265
