### ISSUE TITLE
Migration from Deprecated APIs

### ISSUE THREAD

**Issue by jmbledsoe** [uriyyo/fastapi-pagination#270]
I am currently being bit by https://github.com/uriyyo/fastapi-pagination/issues/228, and so I'm looking to upgrade to the latest version of `fastapi-pagination`. However, the code I'm working on makes use of the previously deprecated, now removed decorator `use_as_page` and function `using_params`. How do you recommend migrating away from those to the new API. Is there a document that describes the changes that ought to be made?

**Comment by uriyyo** [comment]
Hi @jmbledsoe,

Sorry for the long response.

You should remove them and simply call `add_pagination` with your `FasAPI` application instance after you register all routers.

Example:
```py
from fastapi import FastAPI, Depends
from pydantic import BaseModel

from fastapi_pagination import use_as_page
from fastapi_pagination.limit_offset import Page, pagination_params
from fastapi_pagination.paginator import paginate

app = FastAPI()
use_as_page(Page)


class User(BaseModel):
    name: str


users = [User(name='Foo')]


@app.get(
    '/users',
    response_model=Page[User],
    dependencies=[Depends(pagination_params)],
)
async def get_users():
    return paginate(users)
```
Will be migrated to:
```py
from fastapi import FastAPI, Depends
from pydantic import BaseModel

from fastapi_pagination import add_pagination
from fastapi_pagination.limit_offset import Page
from fastapi_pagination.paginator import paginate

app = FastAPI()


class User(BaseModel):
    name: str


users = [User(name='Foo')]


@app.get(
    '/users',
    response_model=Page[User],
)
async def get_users():
    return paginate(users)


add_pagination(app)  # Don't forget to call add_pagination
```

**Comment by uriyyo** [comment]
@jmbledsoe I am closing this issue. Please, reopen it in case of any issues.
