### ISSUE TITLE
Can't get SqlAlchemy example to work

### ISSUE THREAD

**Issue by leechenghan** [uriyyo/fastapi-pagination#283]
I'm following the SqlAlchemy tutorial but keep getting this error

`TypeError: object of type 'Query' has no len()`

Here's my code

```
@router.get("/", response_model=Page[schemas.Transaction])
async def get_transactions(
    start: datetime,
    end: datetime,
    params: Params = Depends(),
    db: Session = Depends(get_db),
):
    return paginate(
        db.query(Transaction).filter(
            Transaction.timestamp >= start, Transaction.timestamp <= end
        ),
        params,
    )
 ```
 
 When I add an `.all()` to the end of my query object, it works.
 
Also, does this library actually help create the pagination query in the SqlAlchemy query builder? Or is it simply paginating whatever results the query returns?

e.g. does it actually add `.limit()` and `.offset()` to the queries? Looking through the code, it doesn't seem like it.

**Comment by uriyyo** [comment]
You should use `pagination` from `fastapi_pagination.ext.sqlalchemy`:
```py
from fastapi_pagination.ext.sqlalchemy import paginate


@router.get("/", response_model=Page[schemas.Transaction])
async def get_transactions(
    start: datetime,
    end: datetime,
    params: Params = Depends(),
    db: Session = Depends(get_db),
):
    return paginate(
        db.query(Transaction).filter(
            Transaction.timestamp >= start, Transaction.timestamp <= end
        ),
        params,
    )
```

Working example - https://github.com/uriyyo/fastapi-pagination/blob/main/examples/pagination_sqlalchemy.py

P.S. Russia  invaded my country Ukraine, I am not able to respond and it can be my last reply😟

**Comment by opyate** [comment]
> P.S. Russia invaded my country Ukraine, I am not able to respond and it can be my last reply

🇺🇦 + 🇪🇺   We stand with you, my friend 👍🏻

**Comment by leechenghan** [comment]
> You should use `pagination` from `fastapi_pagination.ext.sqlalchemy`:
> 
> ```python
> from fastapi_pagination.ext.sqlalchemy import paginate
> 
> 
> @router.get("/", response_model=Page[schemas.Transaction])
> async def get_transactions(
>     start: datetime,
>     end: datetime,
>     params: Params = Depends(),
>     db: Session = Depends(get_db),
> ):
>     return paginate(
>         db.query(Transaction).filter(
>             Transaction.timestamp >= start, Transaction.timestamp <= end
>         ),
>         params,
>     )
> ```
> 
> Working example - https://github.com/uriyyo/fastapi-pagination/blob/main/examples/pagination_sqlalchemy.py
> 
> P.S. Russia invaded my country Ukraine, I am not able to respond and it can be my last reply😟

I hope peace returns to the region soon 🙏

**Comment by uriyyo** [comment]
@leechenghan I am closing this issue. Please, reopen it in case of any issues.
