### ISSUE TITLE
How to pass kwargs arguments  in MOTOR example ? How can I  pass  project={"name": 1} or sorting param?

### ISSUE THREAD

**Issue by marxyes** [uriyyo/fastapi-pagination#297]
Hi team , 
Can anyone help me with how to use , **kwargs  in paginate(),
I want to give sort filed and I want only include fields using **project={"name": 1}**

**Comment by uriyyo** [comment]
HI @marxyes,

Sorry for the long response.

If you want to filter, you should use `query_filter` parameter:
```py
@app.get("/users", response_model=Page[UserOut])
async def get_users() -> Any:
    return await paginate(client.test.users, {"project": {"name": 1}})
```

This integration was done by @zsltg.
@zsltg Could you please help with this question?

**Comment by uriyyo** [comment]
@marxyes I am closing this issue. Please, reopen it in case of any issues.

**Comment by marxyes** [comment]
> @marxyes I am closing this issue. Please, reopen it in case of any issues.

Ok sure , thanks for reply

**Comment by Cimmanuel** [comment]
@uriyyo sorry to bother you, but I think I need more explanation as regards what is what in `{"project": {"name": 1}}`. I also need to filter, but this isn't clear.

**Comment by aduquehd** [comment]
@marxyes You can sort using the `sort` kwarg.

`paginate(collection=collection, query_filter=query_filter, sort=[("_id", -1)])`
