### ISSUE TITLE
Fastapi-pagination Throwing error on linux instance.

### ISSUE THREAD

**Issue by alam-mahtab** [uriyyo/fastapi-pagination#3]
I am working on a project where pagination is working fine but as i take a step forward to host it on AWS EC2 ubuntu instance, it started throwing error like

ERROR: Could not find a version that satisfies the requirement fastapi-pagination==0.5.1
ERROR: No matching distribution found for fastapi-pagination==0.5.1

It also worked fine on heroku,
i am not able to understand that this problem is from AWS or package.

**Comment by uriyyo** [comment]
Which version of python are you using?

The minimal required version is `3.7`.

**Comment by alam-mahtab** [comment]
version is 3.8

**Comment by uriyyo** [comment]
I have tested it using Docker and python 3.8, everything works as expected, cmd that I used:
```bash
$ docker run -it --rm python:3.8 pip install fastapi-pagination==0.5.1
```

Looks like this is a problem on the AWS side because package doesn't have any OS limitations.

Did you resolve this issue?

**Comment by uriyyo** [comment]
@alam-mahtab Any updates?

**Comment by uriyyo** [comment]
Hi @alam-mahtab  is this issue still actual?

**Comment by uriyyo** [comment]
I am closing this issue, in case if it will appear please reopen this issue.
