### ISSUE TITLE
I am facing bellow issue with geeting count of geosptial query on mongo , is there any solution ? while using paginate

### ISSUE THREAD

**Issue by marxyes** [uriyyo/fastapi-pagination#305]
pymongo.errors.OperationFailure: $geoNear, $near, and $nearSphere are not allowed in this context, full error: {'ok': 0.0, 'errmsg': '$geoNear, $near, and $nearSphere are not allowed in this context', 'code': 2, 'codeName': 'BadValue'}

**Comment by uriyyo** [comment]
Hi @marxyes,

I am not an expert on `mongo`(
Maybe someone who has created `mongo` extension can help with it.

**Comment by nikstuckenbrock** [comment]
Hi @marxyes,

I think there is no integration for pymongo yet.
I've created PR #330 to add it.
A quick solution would be to use [Motor](https://github.com/mongodb/motor/) or [Mongoengine](https://github.com/MongoEngine/mongoengine) instead of pymongo.
Hope this helps.

**Comment by uriyyo** [comment]
Hi @nikstuckenbrock @marxyes,

`pymongo` integration has been released under `0.10.0` version.

**Comment by uriyyo** [comment]
Hi @marxyes,

Are you still facing this issue? Could you please provide a code snippet to reproduce this issue?

**Comment by uriyyo** [comment]
Hi @marxyes,

Please, reopen this issue if you still facing this issue
