### ISSUE TITLE
Question: add_pagination(app)

### ISSUE THREAD

**Issue by jordan-carson** [uriyyo/fastapi-pagination#308]
In the example provided for sqlalchemy / postgres it requires to include the below statement before dunder main.

`
add_pagination(app)
`

This sends the entire application, how can we go about including only a subset of all endpoints? Should we create an APIRouter() for the 2 methods that require pagination? 

Please share feedback and thoughts!

**Comment by uriyyo** [comment]
Hi @jordan-carson,

No need to worry about this one. Only endpoints that use `Page` subclass as a `response_model` will be affected, all others will be untouched.

So it's safe to call `add_pagination` on `FastAPI` instance.

**Comment by uriyyo** [comment]
@jordan-carson I am closing this issue. Please, reopen it in case of any issues.
