### ISSUE TITLE
Beanie ODM support

### ISSUE THREAD

**Issue by TamiasSibiricus** [uriyyo/fastapi-pagination#334]
Hi,
I think it would be helpful to add Beanie ODM support for pagination. I'll prepare Pull request in next few days.

**Comment by uriyyo** [comment]
Hi @TamiasSibiricus,

Do you have any plans to implement it?

**Comment by TamiasSibiricus** [comment]
Hi @uriyyo 

Yes.. Just do not complete tests for plugin before my vacation. Will create PR next week.

**Comment by deejaypro** [comment]
Hey,

i just wanted to ask, if you still have plans to create a PR for this? I would like to use this module with my existing Fast-Api+Beanie API.

**Comment by uriyyo** [comment]
Hi @TamiasSibiricus,

Sorry for bothering you. Do you still have plans to implement this integration?

**Comment by uriyyo** [comment]
Hi @deejaypro,

Beanie integration has been added and will be released in the next version.

**Comment by syedhabib53** [comment]
@uriyyo When can we expect next release? We are using right now with git url. 🙄

**Comment by uriyyo** [comment]
@syedhabib53 I hope I will do it in one week

**Comment by marigan** [comment]
fetch_links feature is missing in this implementation unfortunately!

If you have a query where you are searching through nested links you have the have fetch_links=True in the very latest find_many in paginate

**Comment by marigan** [comment]
It can be done like this

```python
async def paginate(
    query: Union[TDocument, FindMany[TDocument]],
    params: Optional[AbstractParams] = None,
    *,
    additional_data: AdditionalData = None,
    fetch_links: bool = False
) -> AbstractPage[TDocument]:
    params, raw_params = verify_params(params, "limit-offset")

    items = await query.find_many(limit=raw_params.limit, skip=raw_params.offset, fetch_links=fetch_links).to_list()
    total = await query.find({}, fetch_links=fetch_links).count()

    return create_page(items, total, params, **(additional_data or {}))
```

anyway there is a bug in beanie while the count won't work here roman-right/beanie#426

**Comment by harshalbaviskar** [comment]
Following workaround should work to get both items as well as count.
```
    fetch_query = query.find_many(limit=raw_params.limit, skip=raw_params.offset, fetch_links=fetch_links)
    items = await fetch_query.to_list()
    total = await query.count()
```

**Comment by Rivosoa** [comment]
Hi @uriyyo , may I know when you will release the version with Beanie support please?

**Comment by uriyyo** [comment]
Hi all,

New version `0.11.0` has been released. Now `fastapi-pagination` supports `beanie`.
