### ISSUE TITLE
Customize LimitOffsetPage 

### ISSUE THREAD

**Issue by tedtally** [uriyyo/fastapi-pagination#335]
I want to alter the LimitOffsetPage response elements to display "records" instead of "items" and "totalCount" instead of "count". I read the link to customize the Page class. Would adding these customizations to the Page class be reflected if we were using LimitOffsetPage classes or can the same modifications to the Page class must be applied to LimitOffset?

**Comment by nikstuckenbrock** [comment]
Hey @tedtally,

in my opinion you should be right. You'll need to create a customized LimitOffsetPage class.
I hope I could help you out.
