### ISSUE TITLE
response_model_exclude is not working

### ISSUE THREAD

**Issue by bestyyo** [uriyyo/fastapi-pagination#340]
here is my code, "response_model_exclude" is no longer useful by using the paginate method. i dont know what goes wrong.

`@router.post('/user/get_users/',`
`             response_model=Page[User],`
`             response_model_exclude=["password", "created_at", "updated_at"])`
`async def get_users(`
`    params: Params = Depends(),`
`    session: AsyncSession = Depends(get_session)`
`):`
`    db_execute = await session.exec(`
`        select(User).where(`
`            User.is_delete == False`
`        ))`
`    users = db_execute.all()`
`    return paginate(users, params)`

**Comment by uriyyo** [comment]
Hi @bestyyo,

You need specify exlude based on a `Page[User]` model instead of `User`.
Please, try yo use this code:
```py
@router.post('/user/get_users/',
     response_model=Page[User],
     response_model_exclude={"items": {"__all__": {"password", "created_at", "updated_at"}}},
)
async def get_users(
    params: Params = Depends(),
    session: AsyncSession = Depends(get_session)
):
    db_execute = await session.exec(select(User).where(User.is_delete == False))
    users = db_execute.all()
  
    return paginate(users, params)
```

**Comment by uriyyo** [comment]
Hi @bestyyo,

You need specify exlude based on a `Page[User]` model instead of `User`.
Please, try yo use this code:
```py
@router.post('/user/get_users/',
     response_model=Page[User],
     response_model_exclude={"items": {"__all__": {"password", "created_at", "updated_at"}}},
)
async def get_users(
    params: Params = Depends(),
    session: AsyncSession = Depends(get_session)
):
    db_execute = await session.exec(select(User).where(User.is_delete == False))
    users = db_execute.all()
  
    return paginate(users, params)
```

**Comment by uriyyo** [comment]
@bestyyo I am closing this issue. Please, reopen it in case of any questions.
