### ISSUE TITLE
page parameter does not start with 0.

### ISSUE THREAD

**Issue by emregeldegul** [uriyyo/fastapi-pagination#345]
Hi.
I migrate from fastapi-pagination==0.7.4 to fastapi-pagination==0.9.3. But, the page argument does not start from zero, it starts from 1. This is causing trouble on the frontend. If I want to start with zero I get the following error.

`
curl -X 'GET' \
  'http://0.0.0.0:8000/users?page=0&size=50'`

`{
  "detail": [
    {
      "loc": [
        "query",
        "page"
      ],
      "msg": "ensure this value is greater than or equal to 1",
      "type": "value_error.number.not_ge",
      "ctx": {
        "limit_value": 1
      }
    }
  ]
}`

**Comment by uriyyo** [comment]
Hi @emregeldegul,

You need to define your own page:
```py
from typing import TypeVar, Generic

from fastapi import FastAPI, Query
from pydantic.types import conint

from fastapi_pagination import Page as BasePage, Params as BaseParams
from fastapi_pagination.bases import RawParams

app = FastAPI()


class Params(BaseParams):
    page: int = Query(0, ge=0)

    def to_raw_params(self) -> RawParams:
        return RawParams(
            limit=self.size,
            offset=self.size * self.page,
        )


T = TypeVar("T")


class Page(BasePage[T], Generic[T]):
    page: conint(ge=0)

    __params_type__ = Params
```

And then you can use it instead of default `Page`:
```py
```

**Comment by emregeldegul** [comment]
I'm understand, thank you!
Such drastic changes are quite damaging to apps :/
