### ISSUE TITLE
Optional pagination

### ISSUE THREAD

**Issue by davidbrochart** [uriyyo/fastapi-pagination#362]
Is it possible to create a route that would return a paginated result if some `params` where passed, and a non-paginated result otherwise?
It looks like `add_pagination` inspects the `response_model`, so I'm not sure how it can be done.

**Comment by uriyyo** [comment]
Hi @davidbrochart,

With version `0.11.0` you can achieve this using `pagination_ctx` function:
```py
from typing import Union, List, Literal, Any

from fastapi import FastAPI, Depends, Query

from fastapi_pagination import Page, paginate, pagination_ctx

app = FastAPI()


@app.get(
    "/",
    response_model=Union[Page[int], List[int]],
    dependencies=[Depends(pagination_ctx(Page[int]))],
)
async def route(
    response_type: Literal["page", "list"] = Query(...),
) -> Any:
    data = [*range(100)]

    if response_type == "page":
        return paginate(data)

    return data


if __name__ == '__main__':
    import uvicorn

    uvicorn.run(app)
```

**Comment by uriyyo** [comment]
@marioland Please, take a look at this comment
https://github.com/uriyyo/fastapi-pagination/issues/455#issuecomment-1329683598

**Comment by uriyyo** [comment]
Hi @davidbrochart,
I am closing this issue, please reopen it if you have more questions.

**Comment by thadk** [comment]
Thanks for this `pagination_ctx` worked perfectly when you have a `Union` where one item is not `*Page[]` on your route `response_model`!

`pagination_ctx` was a bit hard to discover (both reading docs and using LLM) with the error.  It had given an error like #1097 but was unrelated. Maybe there could be some way to add `pagination_ctx` to that error in addition to the other two suggestions, or to the docs?

**Comment by uriyyo** [comment]
Hi @thadk,

Yup, I will update exception message.

I have a dream to update docs to cover all features, cause I guess there are a lot of features that are not covered in docs.

I will try to spend more time on it.
