### ISSUE TITLE
Cursor base pagination 

### ISSUE THREAD

**Issue by fruch** [uriyyo/fastapi-pagination#375]
In some cases, paging by page number isn't exactly accurate (fast pacing changing data)

I would be nice to have some example on how to do those kind of paging (with the databases that support those):

this is almost there (but without utilizing any db capabilities for that):
https://pypi.org/project/fastapi-pagination-utilities/

library doing so for sqlalchemy:
https://github.com/djrobstep/sqlakeyset

**Comment by fruch** [comment]
@uriyyo that PR looks very good, I've played with implementing Cassandra based cassandra-driver cqlengine with it.

One thing I've encountered, is the assumption that the cursor is string.

In Cassandra cases it's bytes, and needs to be treated a bit differently.

Also one minor gotcha, based64 isn't url encoded, it might be nicer to put as url encoded string, so the client can just pass it through without remembering to encode it (not all client code would automatically encode url parameters)

**Comment by uriyyo** [comment]
@fruch Thanks, your points totally make sense. I added support for `bytes` cursor and auto-cursor URL encoding.

To use bytes cursor:
```py
from fastapi_pagination.cursor import CursorPage as BaseCursorPage

CursorPage = BaseCursorPage.with_custom_options(str_cursor=False)
```

**Comment by fruch** [comment]
> @fruch Thanks, your points totally make sense. I added support for `bytes` cursor and auto-cursor URL encoding.
> 
> To use bytes cursor:
> 
> ```python
> from fastapi_pagination.cursor import CursorPage as BaseCursorPage
> 
> CursorPage = BaseCursorPage.with_custom_options(str_cursor=False)
> ```

nice, here a PR using this:
https://github.com/uriyyo/fastapi-pagination/pull/386

**Comment by uriyyo** [comment]
Hi @fruch 

New version 0.11.0 has been released.
