### ISSUE TITLE
Asyncpg issue on paginated query

### ISSUE THREAD

**Issue by ivryan** [uriyyo/fastapi-pagination#38]
Hi,
seems that *asyncpg* pagination doesn't manage correctly **LIMIT** and **OFFSET** clauses because the idx*emphasized text* used to paginate the query uses the regex result on query parameters defined on SQL Text instead the raw parameters

    raw_params = params.to_raw_params()
    items = await conn.fetch(
        f"{query} LIMIT ${idx + 1} OFFSET ${idx + 2}",
        *args,
        *astuple(raw_params),
        )

**Comment by uriyyo** [comment]
Could you please provide more context on where is bug?

Regex is used to calculate the latest index and it's used to correctly add arguments to query.
Looks like it's can be simplified, with putting limit and offset inside query instead of passing it as fetch arguments.

**Comment by ivryan** [comment]
I've checked better the code and it works as expected

Sorry for the misunderstanding

**Comment by uriyyo** [comment]
No worries, actually after looking at code again I have realized that it can be simplified, so thank you for this issue)
