### ISSUE TITLE
Add support for Django >3.2 fastapi-pagination[django]

### ISSUE THREAD

**Issue by jacek-rybak** [uriyyo/fastapi-pagination#397]
It would be nice to have support for the Django versions higher than 3.2.

**Comment by jacek-rybak** [comment]
@uriyyo I added a PR [https://github.com/uriyyo/fastapi-pagination/pull/414] with a Django version upgrade. It would be nice to have it merged as soon as possible, because some projects may be blocked from upgrading Django due not compatible requirements. Unfortunately, this change requires bumping the python version from 3.7 to >=3.8, but I think this is a good move since security support for this version of python ends in 8 months. Thanks for a great lib ;) It's very useful.

**Comment by uriyyo** [comment]
Hi @jacek-rybak 

New version `0.11.0` has been released.
