### ISSUE TITLE
[enh] Use islice rather than slice in order to work with generators.

### ISSUE THREAD

**Issue by masasin** [uriyyo/fastapi-pagination#40]
Right now, you select the data using `[]`. `itertools.islice` stills works on sequences, but also works on generators, which is useful when there is a lot of data to go through.

Specifically, I think replacing this line: https://github.com/uriyyo/fastapi-pagination/blob/b6e287524cffa628e76b87e79d5cab0e6f579035/fastapi_pagination/paginator.py#L17 would be sufficient to add the functionality while changing nothing in the existing API.

The line would become

```items=list(it.islice(sequence, raw_params.offset, raw_params.offset + raw_params.limit]),```

(after `import itertools as it`).

What do you think?

**Comment by uriyyo** [comment]
Hi @masasin,
It looks amazing and very useful.

Would you mind to implement this feature?)

**Comment by masasin** [comment]
I tried submitting a pull request, but the tests are all failing. I can't quite figure out why, and I'm not able to install the environment (EnvCommand error when trying to install psycopg2), so I can't test locally. Can you take a look?

**Comment by lingster** [comment]
psycop2 is the postgres driver. Happy to take a look or would it be useful to add a dockerfile to the project to help reproduce the error and have a consistent development environment setup?

**Comment by elpablete** [comment]
How can I help? Eager to see this resolved!

**Comment by uriyyo** [comment]
I think we should introduce new `paginator` that will be able to work with iterables. Also we should add new pages classes that will not contains `total` field as far as we don't know how many elements are in a iterables and it is not possible to calculate it for infinity generators.

Thats my idea, I am happy to hear yours opinion🙂
