### ISSUE TITLE
Timeline on next release?

### ISSUE THREAD

**Issue by david-welch** [uriyyo/fastapi-pagination#404]
Hello, 
Thanks for the project! There are a couple of features in main I was hoping to use. Do you have any idea when the next release will be?

**Comment by uriyyo** [comment]
Hi @david-welch,

I hope to release a new version in 1-2 weeks

**Comment by qvntz** [comment]
Hi!
Thanks for the project!
I would also like to start using the cursor when it will be released?

**Comment by uriyyo** [comment]
Hi @qvntz 

Sorry, was busy with my main job. I am planning to do it this weekend.

**Comment by uriyyo** [comment]
Hi @david-welch @qvntz 

New version `0.11.0` has been release
