### ISSUE TITLE
Seems using_page is removed now?

### ISSUE THREAD

**Issue by 10ourto** [uriyyo/fastapi-pagination#421]
I need same functionality https://github.com/uriyyo/fastapi-pagination/issues/22 but can't fild `using_page` anymore

**Comment by uriyyo** [comment]
@10ourto I think `set_page` can be what you need.
```py
from fastapi_pagination.limit_offset import Page
from fastapi_pagination import set_page

set_page(Page)
```

But actually with new version of `fastapi-pagination` no need to manually set page cls.

Everything will be done under the hood when you call `add_pagination` on the app instance.
```py
from fastapi import FastAPI

from fastapi_pagination.limit_offset import Page
from fastapi_pagination import add_pagination

app = FastAPI()

@app.get("/", response_model=Page[str])
async def route():
    ...

add_pagination(app)
```

**Comment by uriyyo** [comment]
Hi @10ourto,

Please, reopen this issue in case of more questions.
