### ISSUE TITLE
paginate for sqlalchemy2.0 returns `AbstractPage`, Pylance complains about `.items`

### ISSUE THREAD

**Issue by mbalc** [uriyyo/fastapi-pagination#426]
Ok so my question is - how can I access and map over the items of a page that's returned by the paginator for sqlalchemy 2.0, without getting errors from Pylance?

Here's a screenshot showcasing a toy version of the issue I'm encountering - even though the code itself works when I run it, Pylance complains about the `.items` attribute not defined on the `AbstractPage` class returned from `paginate`
![image](https://user-images.githubusercontent.com/11033790/198054160-b7a074b9-0b55-44be-a34d-b7ad2931bf65.png)

Can this problem somehow be avoided?

the Pylance feature in question can be enabled in VSCode - I only recently discovered that there's a button for that there at the bottom:
![image](https://user-images.githubusercontent.com/11033790/198054939-cf5ee1b5-9eb8-4ed3-a92d-83741827c10a.png)

**Comment by uriyyo** [comment]
Hi @mbalc,

Sorry for the long response.

As an option, you can use `typing.cast` functions:
```
from typing import cast

models_page = cast(Page[Mlmodel], paginate(session, sa.select(Mlmodel), params)
```
