### ISSUE TITLE
Unable to build FastAPI project with fastapi-pagination 0.11.0 dependency on python 3.11

### ISSUE THREAD

**Issue by josecsotomorales** [uriyyo/fastapi-pagination#455]
Hey folks!

I'm getting a dependency issue when building my FastAPI project on Python 3.11, it works fine on 3.10

stack trace:  
```
File "/Users/Jose/Workspace/test-project/venv/lib/python3.11/site-packages/fastapi_pagination/ext/sqlalchemy.py", line 6, in <module>
    from sqlakeyset.paging import (
ModuleNotFoundError: No module named 'sqlakeyset'
```

**Comment by josecsotomorales** [comment]
Tested with fastapi-pagination==0.11.0

**Comment by josecsotomorales** [comment]
Actually! It works well with 0.10.0 so this is not related to Python 3.11, seems like this was introduced on 0.11.0 ... rolling back to 0.10.0 works!

**Comment by uriyyo** [comment]
Hi @josecsotomorales,

Could you please try to install `fastapi-pagination` with `sqalchemy` extras:
```bash
pip install `fastapi-pagination[sqlalchemy]`
```

**Comment by matthew-emw** [comment]
> Hi @josecsotomorales,
> 
> Could you please try to install `fastapi-pagination` with `sqalchemy` extras:
> 
> ```shell
> pip install "fastapi-pagination[sqlalchemy]"
> ```

this resolved the (same) issue for me

**Comment by josecsotomorales** [comment]
That fixes the issue, thanks folks! @uriyyo @matthew-emw 🚀
