### ISSUE TITLE
AbstractPage create method change of signature breaks custom pages

### ISSUE THREAD

**Issue by javivdm** [uriyyo/fastapi-pagination#457]
With the latest release the AbstractPage create method went from 
`def create(cls: Type[C], items: Sequence[T], total: Optional[int], params: AbstractParams) -> C:`
to
`def create(cls: Type[C], items: Sequence[T], params: AbstractParams, **kwargs: Any,) -> C:`

This breaks some pagination calls, I understand adding the kwargs, but the removal of the total parameter looks like an error to me.

If it is not, how should the custom pages be now created?

**Comment by uriyyo** [comment]
Hi @javivdm,

New version `0.11.1` has been released. It has a deprecation warning regarding the old signature.

**Comment by uriyyo** [comment]
P.S. You shouldn't directly create instance of `Page` it should be done using `create_page` function that is called by `paginate` functions:
```py
create_page(items, total, params, **(additional_data or {}))
```

**Comment by sub-Void** [comment]
The deprecation warning is triggered if you simply follow the "Custom Page" section on the docs.
Is this a mistake? It seems to trigger if you add any custom parameters.
