### ISSUE TITLE
SADeprecationWarning in ext/sqlalchemy_future.py

### ISSUE THREAD

**Issue by Popkornium18** [uriyyo/fastapi-pagination#462]
Warning originates here: https://github.com/uriyyo/fastapi-pagination/blob/dbb080a2f0b5c0caeaa8f90c3fa5c428f5a8b02a/fastapi_pagination/ext/sqlalchemy_future.py#L46

This is the warning:
```
.../venv/lib/python3.8/site-packages/fastapi_pagination/ext/sqlalcemy_future.py:46: SADeprecationWarning: Object <sqlalchemy.orm.query.Query object at 0x...> should not be used directly in a SQL statement context, such as passing to methods such as session.execute().  This usage will be disallowed in a future release.  Please use Core select() / update() / delete() etc. with Session.execute() and other statement execution methods.
```

**Comment by uriyyo** [comment]
Hi @Popkornium18,
I guess if you are using `Query` then you should use `paginate` from `fastapi_pagination.ext.sqlalchemy`.

**Comment by uriyyo** [comment]
I will recommend using `mypy`. It will catch bugs like this one.
