### ISSUE TITLE
fastapi-pagination [databases] --> DeprecationWarning

### ISSUE THREAD

**Issue by vadikam100500** [uriyyo/fastapi-pagination#474]
![image](https://user-images.githubusercontent.com/82088927/208082617-36303d47-d1e4-4b30-9159-017ed9ceb502.png)

- test of only 1 funtion with pagination

in file of crud:
```
   from fastapi_pagination.ext.databases import paginate

   async def smx():
       -- logic --
       return await paginate(db=db, query=table.select().where(), params=params)
```

Deprication was fixed by Encode/Databases in last versions

**Comment by uriyyo** [comment]
Hi @vadikam100500,

The new version `0.11.2` has been released and contains a fix for this issue.
