### ISSUE TITLE
How do you get the next page?

### ISSUE THREAD

**Issue by jenia** [uriyyo/fastapi-pagination#49]
Hey Yurii.

How do you get the next page?

I inserted 100 users into the database but I can only see the first page but cannot go to the next.

Thanks

**Comment by uriyyo** [comment]
Hi @jenia,

Can you please provide the code that you are using?

For instance:
https://github.com/uriyyo/fastapi-pagination/blob/98d350dd179d6654f5db6816e09d38be891a3ad2/examples/pagination_sqlalchemy.py#L76-L79

To get second page:
```
http://localhost:8000/users/default?page=1
```

**Comment by jenia** [comment]
Hey @uriyyo 
Thanks for the reply! Yea I was missing the `page=1` parameter. 

Here is my simple example: https://gist.github.com/jenia/1d1c148b52ca8a634dea96a97e926554

Thanks again!!
