### ISSUE TITLE
Possible performance issue

### ISSUE THREAD

**Issue by kamikaze** [uriyyo/fastapi-pagination#5]
https://github.com/uriyyo/fastapi-pagination/blob/3331eb4c02797629fad3688fa55f1f361286f998/fastapi_pagination/paginator.py#L9

Am I missing something or this way of paginating requires to fetch all rows from database to just get full count of rows while we just need a single page of data?

**Comment by uriyyo** [comment]
This is generic pagination that is used to paginate some prefetched data.

In case if you want better performance there are integrations with popular libraries:
* sqlalchemy
* gino
* databases
* orm
* tortoise

The full list of examples can be found [here](https://github.com/uriyyo/fastapi-pagination/tree/main/examples).

For instance `sqlalchemy` pagination usage:
```py
from fastapi_pagination import Page, pagination_params
from fastapi_pagination.ext.sqlalchemy import paginate

...

@app.get("/", response_model=Page[UserOut], dependencies=[Depends(pagination_params)])
def get_users(db: Session = Depends(get_db)) -> Any:
    return paginate(db.query(User))

```

**Comment by kamikaze** [comment]
Nice. thanks!
