### ISSUE TITLE
How do I use the customization feature?

### ISSUE THREAD

**Issue by jenia** [uriyyo/fastapi-pagination#50]
I [tried to customize][1] FastAPI-pagination. I began implementing the AbstractPage class but I'm stuck. I don't understand how customization works. I wanted it to display the `Pagination` class as `"links" : {"next" : 1, "page" : 0}` for example instead of `total":102,"page":0,"size":50` by

Can you please give me a hint on how to achieve this?

Thanks!

  [1]: https://gist.github.com/jenia/83a8f4fcc4fd2ade04070314aa2e4522

**Comment by jenia** [comment]
I think I need to change `return cls(results=users)` :) `Typing` syntax threw me off a little

**Comment by uriyyo** [comment]
Hi @jenia,
Can I close this issue or you have more questions?

**Comment by uriyyo** [comment]
Hi @jenia,

I am closing this issue. Feel free to reopen it)
