### ISSUE TITLE
Update the sessionlocal if the database table periodically updated

### ISSUE THREAD

**Issue by swicaksono** [uriyyo/fastapi-pagination#508]
Hi, this is very extraordinary project. I just try to use this library to serve the data that stored in postgres DB. Im curious what will happen if the DB table periodically updated while the API running? Is the previous state will be updated so as the total data on the response page or we need to make to update the sessionlocal periodically? If so, how to do that? Thank you.

**Comment by uriyyo** [comment]
Hi @swicaksono,

I'm sorry for not getting back to you sooner.

No need to worry about that, `paginate` functions don't have any caching logic, you will always receive the newest available data.

**Comment by uriyyo** [comment]
I'm closing this issue. Please, reopen it if you still have questions.
