### ISSUE TITLE
Getting error when using sqlalchemy2.0 style

### ISSUE THREAD

**Issue by jenn0pal** [uriyyo/fastapi-pagination#555]
`paginate(session.execute(select(Model)).all())` returns TypeError: list.count() takes exactly one argument (0 given)

**Comment by arthurio** [comment]
@jenn0pal I'm guessing you are using the sqlalchemy paginate, just remove `.all()` and it should work 👍🏻

**Comment by jenn0pal** [comment]
@arthurio session.execute() returns ChunkedIteratorResult and so it also doesn't have the count() metho
`AttributeError: 'ChunkedIteratorResult' object has no attribute 'count'`

**Comment by arthurio** [comment]
My bad, it's `paginate(session, select(Model))`

**Comment by jenn0pal** [comment]
Ah! got it. Also my mistake, I was using `sqlalchemy` instead of `sqlalchemy_future`
