### ISSUE TITLE
Ability to convert DB returned data to API schema

### ISSUE THREAD

**Issue by plaa** [uriyyo/fastapi-pagination#581]
I was unable to find any instructions in the documentation on how to convert DB returned data to the schema returned by the API.

For example, we have a query that returns:
```
{
    invitation_email: "joe@example.com",
    user_first_name: "Joe",
    user_last_name: "Shmoe"
}
```

We want the API to return this as:
```
{
    invitation_email: "joe@example.com",
    user: {
        first_name: "Joe",
        last_name: "Shmoe"
    }
}
```

Is there some mechanism for this already?  I think it might be possible to do such conversions using Pydantic model validators, but that seems very awkward and contrary to the point of validators.

**Comment by uriyyo** [comment]
Hi @plaa,

I guess you can try to use `sqlalchemy.orm.Bundle`. Query will look like this:
```py
query = select(
    User.email.label("invitation_email"),
    Bundle(
        "user",
        User.first_name,
        User.last_name,
    )
)
```

Then you can call `paginate` with this query.

**Comment by plaa** [comment]
Hi @uriyyo!

Thanks, that probably will be sufficient for our current need.

However, from an architectural point of view, the current design is less than optimal.  Currently it tightly couples the SQL-query to the API response returned by a router, which should be as lightly coupled as possible.  It would be much clearer if you could write a clean SQL query, then paginate it, convert the SQL results into the desired format using a lambda function passed in to paginate, and then have FastAPI cast it into the desired API output schema.

In our current project we've started using a three-layer mechanism, where we explicitly define the API schema, domain model schema and DB schema separately, just to reduce the coupling between logic layers.  Adding the conversion option to the pagination would help this pain a lot.

**Comment by uriyyo** [comment]
@plaa Makes sense to me, I will try to add a feature that will allow doing things like you mentioned.

**Comment by plaa** [comment]
@uriyyo Regarding the API for conversion, I suggest instead of a function that takes a single item and converts that (which I originally suggested), to have a function that takes the array of items and returns the converted array, and allow the function to be async.  This allows making additional queries / API calls to further populate the paged items.  (The whole array is needed so additional queries can be bundled instead of hitting the DB once per paged item.)

We hit a point where we simply can't extend the single query further (multiple array_agg's and json packaging and outer-join-null-exclusions), so we had to give up the use of `paginate` for now and instead fetch the data manually.  Even if the single query would be technically possible, it would be a monstrosity to maintain.

I believe the natural place would be after fetching the items and before calling `create_page`.  The conversion function can take the raw ORM objects as input since it can be ORM-specific.  It's pretty clear how to add it in `ext/gino.py` but not sure whether there would be a more generic location for the conversion.

**Comment by dominikberse** [comment]
+1 for this. I like the simplicity, but I need to apply some custom conversion to the database objects as well, which currently stops me from using this library.

**Comment by uriyyo** [comment]
@plaa @dominikberse 

`paginate` functions now will have `transformer` argument, also `transformer` can be specified using `pagination_ctx`:
```py
from typing import Sequence

from fastapi_pagination import Page, add_pagination, paginate, pagination_ctx
from fastapi import FastAPI, Depends

app = FastAPI()
add_pagination(app)


def transformer(items: Sequence[int]) -> Sequence[int]:
    return [item * 2 for item in items]


@app.get(
    "/implicit",
    dependencies=[
        Depends(pagination_ctx(transformer=transformer)),
    ]
)
def route1() -> Page[int]:
    return paginate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


@app.get("/explicit")
def route2() -> Page[int]:
    return paginate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], transformer=transformer)
```

`transformer` can be async function.

**Comment by uriyyo** [comment]
Hi @dominikberse @plaa,

This feature has been released under version `0.12.0`.

**Comment by uriyyo** [comment]
I am closing this issue. Please, reopen it in case of any questions.

**Comment by plaa** [comment]
Thanks @uriyyo !  I took that into use today and it works great.  Allows making much simpler and cleaner SQL queries.
