### ISSUE TITLE
Add support for Django orm

### ISSUE THREAD

**Issue by lingster** [uriyyo/fastapi-pagination#60]
Hi, 
I was wondering if you can review the PR: https://github.com/uriyyo/fastapi-pagination/pull/59

This adds a new extension to be used with Django. One problem was how to map from a django model to a pydantic model, so I updated paginate() to access a BaseModel which expects a from_django() method to convert from django to a pydantic model. 

I was also considering [djantic](https://github.com/jordaneremieff/djantic) as a possible solution. 
Open to your thoughts for improvements!
Thanks,
Ling

**Comment by uriyyo** [comment]
Hi @lingster,

Thank you for your efforts🙂
