### ISSUE TITLE
Error with JSON/JSONB on version 12.x

### ISSUE THREAD

**Issue by ikkysleepy** [uriyyo/fastapi-pagination#627]
I get an error when there is a field with JSON/JSON B. on version 12.x

I get this error: 
```
Can't apply uniqueness to row tuple containing value of type JSONB(astext_type=Text()); this datatype produces non-hashable values
```

This was working on an older version of fastapi-pagination, version 11.2, but stopped working on version 12.0

I did get a warning though on some tables that had :

```
SAWarning: SELECT statement has a cartesian product between FROM element(s) "steps_text" and FROM element "procedure_statuses".  Apply join condition(s) between each element to resolve.
  total = conn.scalar(count_query(query))
```

but on my log table I don't get an error on version 11.2, so the issue seems to be related to some changes on 12.x

Note: I did try the unique flag but it doesn't seem to be working correctly either and I get other errors.

**Comment by uriyyo** [comment]
Hi @ikkysleepy,

I am closing this issue, please reopen it in case if issue still exists

**Comment by FanchenBao** [comment]
I have a similar error

```
Can't apply uniqueness to row tuple containing value of type ARRAY(String()); this datatype produces non-hashable values
```

Adding `unique=False` to the `paginate` function resolved the problem.

HOWEVER, what does this `unique` parameter do? I couldn't find any info on the documentation. Can you offer some insights? Thanks! @uriyyo
