### ISSUE TITLE
Using sort on motor 

### ISSUE THREAD

**Issue by koushik355** [uriyyo/fastapi-pagination#649]
Hi, thanks for such an amazing package. I've used it very extensively with PostgreSQL. Really made life a lot easier—just one query. 
Currently, I'm using it with MongoDB using motor. 
I want to sort using a key, how do I do that? 

```
notifications = await paginate(
        collection=notification_collection,
        query_filter=query,
        params=params
    )
```

I want to sort the notifications based on `created_at` key which exist in the collection. How do I do that? Thank you in advance.

**Comment by uriyyo** [comment]
Hi @koushik355,

Unfortunately sorting is not supported at this moment.

I will try to add this feature and release it ASAP.

**Comment by koushik355** [comment]
Thank you. @uriyyo

**Comment by koushik355** [comment]
Hi, for `pymongo`, sorting is missing. Please check that. Thank you. @uriyyo

**Comment by uriyyo** [comment]
Hi @koushik355,

`pymongo` sort has been released, I am closing this issue.
