### ISSUE TITLE
TypeError: type 'Collection' is not subscriptable when using pymongo

### ISSUE THREAD

**Issue by hairshkumar** [uriyyo/fastapi-pagination#652]
Hi am using FastAPI with pymongo to retrieve data from mongo currently am using fastapi_pagination.ext.pymongo.paginate to paginate the mongo collection results.

The parameter **collection: Collection[T]** - causes the issue below.
```
File "/opt/homebrew/lib/python3.11/site-packages/fastapi_pagination/ext/pymongo.py", line 16, in <module>

    collection: Collection[T],

TypeError: type 'Collection' is not subscriptable
```
If I change **Collection[T] to Collection**, I can see the warning log in the console also it working fine for me.

- python -3.11 
- fastapi - 0.95.0
- uvicorn - 0.21.1
- pymongo -3.10.0 

Please advise on how to fix these issue

**Comment by uriyyo** [comment]
Hi @hairshkumar,

Could you please update `pymongo` version to latest one (`4.3.3`)?

**Comment by hairshkumar** [comment]
Hi @uriyyo 

After upgrading **pymongo=4.3.3** am getting below error.

NameError: name 'Collection' is not defined

**Comment by uriyyo** [comment]
Hmmm, that's strange.

Does code bellow works on your env?
```py
from typing import Any, Mapping, TypeVar

from pymongo.collection import Collection

T = TypeVar("T", bound=Mapping[str, Any])


def foo(collection: Collection[T]) -> Collection[T]:
    return collection
```

It works for me with:
```
python 3.11.0
pymongo 4.3.3
```

**Comment by hairshkumar** [comment]
It working now with pymongo=4.3.3. It would be great if you tell me why its not working in previous version of pymongo.

**Comment by uriyyo** [comment]
Could you please update `fastapi-pagination` version to `0.12.3`? It should work with new version

**Comment by uriyyo** [comment]
@hairshkumar Any updates?

**Comment by uriyyo** [comment]
@hairshkumar I am closing this issue. Please, reopen it in case the issue still exists.
