### ISSUE TITLE
TypeError: unhashable type: 'dict' when unique defaults to True in _old_paginate_sign

### ISSUE THREAD

**Issue by jshields** [uriyyo/fastapi-pagination#665]
https://github.com/uriyyo/fastapi-pagination/blob/fcfc2b02dfee379f93125e2c47e643af3472d22c/fastapi_pagination/ext/sqlalchemy.py#L223

It seems as though I am blocked until I move onto SQLAlchemy 2.0 syntax, so that I can set `unique=False`, otherwise `_maybe_unique` attempts to compare uniqueness of JSON `dict`s which fails giving this error:

`TypeError: unhashable type: 'dict'`

Is there a suggested workaround? Note that my `Query` has a `.distinct()` applied to it so I don't need uniqueness checked. Thank you.

In the meantime, this isn't a big deal because I can continue using package version 0.11.4 which supports `Query` (until I migrate to SQLAlchemy 2.0 style syntax)
https://github.com/uriyyo/fastapi-pagination/blob/fcfc2b02dfee379f93125e2c47e643af3472d22c/fastapi_pagination/ext/sqlalchemy.py#L137-L161

**Comment by uriyyo** [comment]
Hi @jshields,

New version `0.12.4` has been released.

Now you can use `unique` with `sqlachemy.orm.Query`.

**Comment by jshields** [comment]
The original error is gone and I think this issue can be closed. However pagination still doesn't work for me because I end up with a list of tuples containing the values for the rows, which fails Pydantic validation. I believe it may be related to this note from the SQLAlchemy 1.4 to 2.0 migration guide:
> Return results are in terms of a [Result](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result) object, the new version of the SQLAlchemy ResultProxy object, which also adds many new methods for compatibility with [Query](https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html#sqlalchemy.orm.Query), including [Result.one()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.one), [Result.all()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.all), [Result.first()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.first), [Result.one_or_none()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.one_or_none), etc.

> The [Result](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result) object however does require some different calling patterns, in that when first returned it will always return tuples and it will not deduplicate results in memory. In order to return single ORM objects the way [Query](https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html#sqlalchemy.orm.Query) does, the [Result.scalars()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.scalars) modifier must be called first.

https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-20-unify-select

Once I get onto SQLAlchemy 2.0 query syntax, I will retest with the latest version of the fastapi-pagination package. In the meantime an older version of the package works with the older 1.x query syntax.

**Comment by uriyyo** [comment]
@jshields Great, I am closing this issue.
