### ISSUE TITLE
How to use joinedload options when using sqlalchemy

### ISSUE THREAD

**Issue by fshmng09** [uriyyo/fastapi-pagination#691]
Hello!
I am trying to use joinedload with sqlalchemy but it seems overwriting original query because of passing by reference.
https://github.com/uriyyo/fastapi-pagination/blob/0ce8f30e321caece96a2ba6c0261f9a230d78ec2/fastapi_pagination/ext/sqlalchemy.py#L55

Are there any way to use options when using sqlalchemy?

**Comment by uriyyo** [comment]
Hi @fshmng09,

It actually doesn't override your original query. `sqlalchemy` creates a new query object when you call most of the query methods:
```py
assert query is not query.order_by(None)
```

**Comment by fshmng09** [comment]
@uriyyo 
Hi! Thank you for you reply!

I have created a code to reproduce the problem.

https://github.com/fshmng09/fastapi-pagination-postgres-sample

In this sample, user-todo has a 1-to-N relationship.
When the list of users is GETted, the todo associated with the user is printed.
Also, when the query is executed, the sql statement is printed.

We consider three patterns: 
1. `GET:/users`
2. `GET:/joined-users`
3. `GET:/paged-joined-users`.
Each log is stored under `logs/`.


When executing `GET:/users`, the query is executed multiple times.
In the case of `GET:/joined-users` , the query is executed only once at first.

In `GET:/paged-joined-users`, paging is added and printed. In fact, the query is executed multiple times, just as it would be if it were not joinedloaded.

This is a major performance concern for complex table.
I would like to solve this problem.

**Comment by uriyyo** [comment]
https://github.com/fshmng09/fastapi-pagination-postgres-sample/blob/dea5c672dccea9ca3fcaec2f0ee11a29428d3ddb/app/endpoints.py#L69

Please, replace replace `joinedload` with `selectinload`:
```py
from sqlalchemy.orm import selectinload

@api_router.get("/paged-joined-user", response_model=Page[schema.User])
def get_paged_joined_users(db: Session = Depends(deps.get_db), params: Params = Depends()) -> Page[schema.User]:
    paged_users = paginate(db.query(models.User).options(
        selectinload(models.User.todos)
    ), params)
    print_for_check_query(paged_users.items)
    return paged_users
```

You will have 3 queries being executed:
1. To get total count of rows.
2. To load rows chunk.
3. To load relationships.

**Comment by fshmng09** [comment]
@uriyyo 
Thank you for your checking!!
I made a mistake with get_joined_users.txt in the previous repository. My sincere apologies.

I also tried selectinload as you suggested, but it seems that todoos are selected by the number of todos. subqueryload is the same. (total of four queries are executed, two of which refer to the todo table.)

I pushed the above two fixes to the sample repository.

**Comment by fshmng09** [comment]
@uriyyo 
Hello.
When I tried items=query.all() here, the joinedload is done as expected and the N+1 problem is solved.
https://github.com/uriyyo/fastapi-pagination/blob/0a06e664e13825c6df2be8acb962180fe4bc533a/fastapi_pagination/ext/sqlalchemy.py#L115

**Comment by uriyyo** [comment]
@fshmng09 Hmm, that's interesting, I will take a look

**Comment by uriyyo** [comment]
@fshmng09 New version `0.12.5` has been released. This issue should be fixed now.

**Comment by fshmng09** [comment]
@uriyyo 
Thank you so much.
It is working well now!!

**Comment by uriyyo** [comment]
Great, happy to hear that
