### ISSUE TITLE
Surpressing FastAPIPaginationWarning with sqlalchemy

### ISSUE THREAD

**Issue by capkz** [uriyyo/fastapi-pagination#711]
I am trying to surpress this warning:
```
Package "sqlalchemy" is installed.

It's recommended to use extension "fastapi_pagination.ext.sqlalchemy" instead of default 'paginate' implementation.

Otherwise, you can disable this warning by adding the following code to your code:
warnings.simplefilter("ignore", FastAPIPaginationWarning)
```

I have tried to surpress it like mentioned with this piece of code, I tried using it everywhere, even at the top of main.py:
```Python
import warnings
from fastapi_pagination.util import FastAPIPaginationWarning

warnings.simplefilter("ignore", FastAPIPaginationWarning)
```

**Comment by capkz** [comment]
> Hi @capkz,
> 
> The code below will not generate any warnings:
> 
> ```python
> import warnings
> 
> from fastapi import FastAPI
> from pydantic import BaseModel
> 
> from fastapi_pagination import Page, add_pagination, paginate
> from fastapi_pagination.utils import FastAPIPaginationWarning
> 
> warnings.simplefilter("ignore", FastAPIPaginationWarning)
> 
> app = FastAPI()
> 
> 
> class UserOut(BaseModel):
>     name: str
>     surname: str
> 
> 
> users = [
>     UserOut(name="Steve", surname="Rogers"),
> ]
> 
> 
> @app.get("/users")
> async def get_users() -> Page[UserOut]:
>     return paginate(users)
> 
> 
> add_pagination(app)
> 
> if __name__ == "__main__":
>     import uvicorn
> 
>     uvicorn.run(app)
> ```

I have done it this way as well, I have just realised that I am able to supress the errors when the app runs.

But when I do a router test with Pytest, the errors are no longer suppressed. Example:

```Python
@pytest.fixture(scope="class")
def test_client():
    with TestClient(app) as test_client:
        yield test_client

def test_getting_all_paginate_values_is_successful(self, test_client):
    response = test_client.get("/values/")
    assert response.status_code == 200
```

This results in the warning, even if I add the supress in the pytest file.

**Comment by uriyyo** [comment]
Could you add this config to `pytest.ini`:
```ini
[pytest]

filterwarnings =
    ignore::fastapi_pagination.utils.FastAPIPaginationWarning:.*:
```

**Comment by capkz** [comment]
> Could you add this config to `pytest.ini`:
> 
> ```ini
> [pytest]
> 
> filterwarnings =
>     ignore::fastapi_pagination.utils.FastAPIPaginationWarning:.*:
> ```

This does work, thank you so much for your swift reply and help!!

**Comment by uriyyo** [comment]
Great, happy to help you✨
