### ISSUE TITLE
Start working on pydantic v2 support

### ISSUE THREAD

**Issue by nicoekkart** [uriyyo/fastapi-pagination#714]
Pydantic v2 is currently in beta and fastapi now also has a beta version running. When trying to update, I run into problems because of this library due to the usage of generics. 

Is there already work being done on allowing Pydantic V2 with this project?

**Comment by uriyyo** [comment]
Hi @nicoekkart,

I will take a look.

**Comment by nicoekkart** [comment]
Great! Thanks

**Comment by uriyyo** [comment]
Hi @nicoekkart,

New version `0.12.5` has been released. Issue with `generics` should be fixe now.

**Comment by tworedz** [comment]
Based on changes in this PR https://github.com/uriyyo/fastapi-pagination/pull/715, it still produces warning, because pydantic v2 still backport some imports:
with warning for `GenericModel` from version [(v2.1.0)](https://docs.pydantic.dev/latest/changelog/#v210-2023-07-25)
```
/Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-0I7teBBe-py3.11/lib/python3.11/site-packages/pydantic/_migration.py:276: UserWarning: `pydantic.generics:GenericModel` has been moved to `pydantic.BaseModel`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
```

Instead, we need to rely on `IS_PYDANTIC_V2` constant, like so:

From this:
```python
if TYPE_CHECKING:
    from pydantic import BaseModel as GenericModel
else:
    try:
        from pydantic.generics import GenericModel
    except ImportError:  # pragma: no cover
        GenericModel = BaseModel
```
to this:
```python
if IS_PYDANTIC_V2:
    from pydantic import BaseModel as GenericModel
else:
    from pydantic.generics import GenericModel
```

If it speeds up solving this, I can create PR

**Comment by tworedz** [comment]
Hi, @uriyyo 

Is it possible to issue tag with #767 fix? Would be very nice!)

**Comment by uriyyo** [comment]
@tworedz Yup, I will do it today

**Comment by uriyyo** [comment]
@tworedz New version `0.12.7` has been released

**Comment by tworedz** [comment]
Thank you so much!)

**Comment by uriyyo** [comment]
I am closing this issue. Please, reopen it if the issue will appear again.
