### ISSUE TITLE
Motor pagination with "aggregate"

### ISSUE THREAD

**Issue by jochman** [uriyyo/fastapi-pagination#751]
Hey, I'm trying to paginate over aggregate (using time series) and the `fastapi_pagination.ext.motor.paginate` seems to work only with `find`. 

Am I missing something or it's not supported (yet)?

**Comment by uriyyo** [comment]
Hi @jochman,

There is `fastapi_pagination.ext.motor.paginate_aggregate` extension. Could you please try to use it?
