### ISSUE TITLE
 limit=0 throwing an exception error

### ISSUE THREAD

**Issue by f616** [uriyyo/fastapi-pagination#770]
I'm getting errors when I make a call with limit=0.

`http://127.0.0.1:8000/apiLimit/employees/all?limit=0&offset=0`

`File "C:\Users\xxx\AppData\Local\pypoetry\Cache\virtualenvs\python-fastapi-pagination-fpfShGP7-py3.11\Lib\site-packages\pydantic\main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for LimitOffsetParams
limit
  Input should be greater than or equal to 1 [type=greater_than_equal, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.1/v/greater_than_equal`

I totally understand that calling limit=0 should not be valid, but is there any option to avoid throwing an exception error?

My sample code is the following

`@app.get(path="/apiLimit/employees/all", name="Gets all employees", response_model=LimitOffsetPage[EmployeeOut])
async def get_all_employees():
conn = connect_to_db()
results = conn.query(Employee).all()
return paginate(results)`

**Comment by josecsotomorales** [comment]
This also hit me up, should `fastapi-pagination `return like a `fastapi.HTTPException` instead of a validation error? So the error gets surfaced to the user's response, on my case, it's happening with something like: 

```
client.get("/items?size=250")
```

**Comment by uriyyo** [comment]
Hi @f616 @josecsotomorales,

Thanks for reporting this issue, it's pydantic v2 integration issue.

**Comment by josecsotomorales** [comment]
Thanks for the quick turnaround @uriyyo, do we have an expected date for a release with this fix?

**Comment by uriyyo** [comment]
@josecsotomorales I will do it on a weekend

**Comment by josecsotomorales** [comment]
Nice! Happy to help in whatever's needed, just ping me

**Comment by uriyyo** [comment]
@josecsotomorales @f616 Fix was released under version `0.12.8`

**Comment by josecsotomorales** [comment]
Thank you @uriyyo 🚀
