### ISSUE TITLE
Add filter fields in mongoDB pagination

### ISSUE THREAD

**Issue by heldergomes** [uriyyo/fastapi-pagination#782]
It's really helpful filter fields in order to avoid high consumption of network, I've been trying to find a way to filter fields in the same way as pymongo does nowadays through this lib, however I didn't find any possibility to implement that.

I'd like to implement a new field in the paginate function for mongodb, where it's possible to pass filters through a filter field.

**Comment by uriyyo** [comment]
@heldergomes This feature should be available under version `0.12.8`.
