### ISSUE TITLE
Performance issue with SQLAlchemy using asyncio

### ISSUE THREAD

**Issue by plaa** [uriyyo/fastapi-pagination#787]
Hi,

I noticed that the sqlalchemy extension supports async connections by internally utilizing the corresponding synchronous connection:

https://github.com/uriyyo/fastapi-pagination/blob/main/fastapi_pagination/ext/sqlalchemy.py#L129-136

To my understanding, using the synchronous connection will block the asyncio event loop of the entire application for the duration of the paginated query.  Thus many / slow paginated queries could impact performance greatly.

Is this concern warranted or am I missing some details how the asyncio event loop works?  I haven't run any tests, just concerned based on reviewing the code.

Thanks for you hard work!

**Comment by uriyyo** [comment]
Hi @plaa,

Thanks for question.

If you will take a look at how `sqlachemy` `AsyncSession` works you will see that it actually spawns `greenlet` thread and uses `sync_session` instance:

https://github.com/sqlalchemy/sqlalchemy/blob/16725b95237ee9af10e3fc16e6a17909c04a89bf/lib/sqlalchemy/ext/asyncio/session.py#L429-L462

You can find more details here - https://docs.sqlalchemy.org/en/20/changelog/migration_14.html#asynchronous-io-support-for-core-and-orm

`fastapi-pagination` `sqlachemy` extension basically follows the same pattern as `sqlachemy` does:
https://github.com/uriyyo/fastapi-pagination/blob/fb915bedf2dcde91caea6dad4e1646aa298d0989/fastapi_pagination/ext/sqlalchemy.py#L192-L205

**Comment by plaa** [comment]
Thank you for the prompt answer @uriyyo !  I wasn't aware that async/sync code could be mixed like that using the greenlet library, thanks for enlightening me.
