### ISSUE TITLE
option to return all rows

### ISSUE THREAD

**Issue by lingster** [uriyyo/fastapi-pagination#80]
hi, would it be possible to add a feature to the parameter to return all rows? maybe either a boolean for all rows or -1 in the size field.

Happy to submit a PR..

**Comment by uriyyo** [comment]
Hi @lingster,
Sorry for the long response. Could you please provide examples?

Basically, the idea of pagination is to prevent the full loading of all entities.

You can always create a custom page and increase max number of page size.

**Comment by uriyyo** [comment]
I will close this one, you can open it in case if you will have more ideas.
