### ISSUE TITLE
Pagination is not working with tortoise-orm version 0.20.0

### ISSUE THREAD

**Issue by xalien10** [uriyyo/fastapi-pagination#842]
Hi!

I'm trying to use pagination with the latest version of `tortoise-orm (0.20.0)` according to the [official integration tortoise-orm example](https://github.com/uriyyo/fastapi-pagination/blob/main/examples/pagination_tortoise.py).
But it's not working and getting pydantic model serialization error.

Later tried the following and it's working with the default `paginate` method like below.
```python
from typing import Any

from fastapi import Depends
from fastapi_pagination import Params, paginate, Page

from apps.contacts.models import Country
from apps.utils.cbv.routers import InferringRouter
from apps.utils.cbv.views import cbv


router = InferringRouter()


@cbv(router)
class CountryViews:
    @router.get("/countries", response_model=Page[Any], tags=["address"])
    async def country_list(self, params: Params = Depends()) -> Any:
        return paginate(await Country.all().values(), params=params)

```

I'm using [cbv](https://fastapi-utils.davidmontague.xyz/user-guide/class-based-views/) and [InferringRouter](https://fastapi-utils.davidmontague.xyz/user-guide/inferring-router/)  from [FastAPI utils](https://fastapi-utils.davidmontague.xyz/user-guide/class-based-views/).
As they don't have support for Pydantic version 2.0 yet, so I've copied two modules in my local utility packages so that I can use them with Pydantic version 2.0.

Can you please tell me what  I can do to use the tortoise-orm integration version of `fastapi-pagination` instead of  default `paginate`?
@uriyyo

**Comment by uriyyo** [comment]
@xalien10 I fixed example, it should work now.

**Comment by xalien10** [comment]
@uriyyo 
I'm sorry but actually it doesn't work. It's having the same problem. May be you can take a look that the following error message to shed some light on the darkness
<img width="1400" alt="Screenshot 2023-09-26 at 7 00 09 PM" src="https://github.com/uriyyo/fastapi-pagination/assets/17931458/271bc568-a79c-4e15-b0f9-f590a62d99fa">

**Comment by uriyyo** [comment]
@xalien10 That because `Country` is not valid pydantic type:
```py
from typing import Any

from fastapi import Depends
from fastapi_pagination import Params, Page
from fastapi_pagination.ext.tortoise import paginate
from tortoise.contrib.pydantic import pydantic_model_creator

from apps.contacts.models import Country
from apps.utils.cbv.routers import InferringRouter
from apps.utils.cbv.views import cbv


router = InferringRouter()

CountrySchema = pydantic_model_creator(Country)


@cbv(router)
class CountryViews:
    @router.get("/countries", response_model=Page[CountrySchema], tags=["address"])
    async def country_list(self, params: Params = Depends()) -> Any:
        return paginate(Country, params=params)
```

**Comment by xalien10** [comment]
Thank you for pointing it out. 🙂  Now it's working. There was another thing that was also responsible for this serialization error is the reverse relation to other model. 
My pydantic schema of the Tortoise database Model is like below:
```
from tortoise.contrib.pydantic.creator import pydantic_queryset_creator, pydantic_model_creator

from apps.contacts.models import Country

Country_Pydantic = pydantic_model_creator(Country, name="Country", exclude_readonly=True)
```
