### ISSUE TITLE
Using AsyncSession doesnt return results, getting an error

### ISSUE THREAD

**Issue by rsingh2411** [uriyyo/fastapi-pagination#849]
I am using fastapi fasapi-pagination with postgres,

if i use from fastapi_pagination.ext.sqlalchemy import paginate
then 

```
    async def get_paginated_data(self, db_session: AsyncSession) -> Page[ModelType]:
        query = select(User)

        return await paginate(db_session, query)
```

getting following errors
```

  File "/Users/rohitsingh/Workspace/CloudGain/test/ces-fastapi-backend/app/controllers/user.py", line 23, in get_paginated_users
    return await self.user_repository.get_paginated_data()
  File "/Users/rohitsingh/Workspace/CloudGain/test/ces-fastapi-backend/core/repository/base.py", line 73, in get_paginated_data
    return await paginate(self.session,query)
  File "/Users/rohitsingh/Workspace/CloudGain/test/ces-fastapi-backend/testenv/lib/python3.11/site-packages/fastapi_pagination/ext/sqlalchemy.py", line 208, in paginate
    return exec_pagination(query, params, conn, transformer, additional_data, subquery_count, unique, async_=False)
  File "/Users/rohitsingh/Workspace/CloudGain/test/ces-fastapi-backend/testenv/lib/python3.11/site-packages/fastapi_pagination/ext/sqlalchemy.py", line 120, in exec_pagination
    items = _maybe_unique(conn.execute(query), unique)
  File "/Users/rohitsingh/Workspace/CloudGain/test/ces-fastapi-backend/testenv/lib/python3.11/site-packages/fastapi_pagination/ext/sqlalchemy.py", line 67, in _maybe_unique
    return (result.unique() if unique else result).all()

```

after reloading the app following is seen in the logs

```
sys:1: RuntimeWarning: coroutine 'async_scoped_session.execute' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
sys:1: RuntimeWarning: coroutine 'async_scoped_session.scalar' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

DB fetching logic is referred from https://github.com/iam-abbas/FastAPI-Production-Boilerplate/blob/main/core/database/session.py

Any thoughts on this, where it might have gone wrong from my side.
if following is used then it works fine

```
from fastapi_pagination import paginate

 async def get_paginated_data(self) -> Page[ModelType]:
        query = select(self.model_class)
        users = await self.session.scalars(query)

        return paginate(users.all())
```

**Comment by uriyyo** [comment]
No need to fetch all rows, just pass `query` to `paginate` function:
```py
from fastapi_pagination import paginate

 async def get_paginated_data(self) -> Page[ModelType]:
        query = select(self.model_class)
        return await paginate(self.session, query)
```

**Comment by rsingh2411** [comment]
@uriyyo   

My bad I am getting the same issue with query , my code in previous snippet was not correct , if you follow the stack trace I have used query also

from fastapi_pagination.ext.sqlalchemy import paginate

    async def get_paginated_data(self, db_session: AsyncSession) -> Page[ModelType]:
        query = select(User)
        return await paginate(db_session, query)

**Comment by RohitSingh-GSLab** [comment]
After debugging found out that 

Since the DB fetching logic is referred from https://github.com/iam-abbas/FastAPI-Production-Boilerplate/blob/main/core/database/session.py. The session object is of type async_scoped_session where as the in sqlalchemy.py  AsyncConn types are AsyncSession, AsyncConnection

AsyncConn: TypeAlias = "Union[AsyncSession, AsyncConnection]"

In my case it was dependency get_session method  was returning <class 'sqlalchemy.ext.asyncio.scoping.async_scoped_session'> hence the code was not working

after modifying code to this, it started working

    ```
async def get_paginated_data(self) -> Page[ModelType]:
        query = select(self.model_class)
        async_connection = await self.session.connection()
        return await paginate(async_connection,query)
```

**Comment by uriyyo** [comment]
Hi @RohitSingh-GSLab @rsingh2411,

New version `0.12.11` has been released, this issue should be fixed now.

Could you please verify it?

**Comment by RohitSingh-GSLab** [comment]
Upgraded to 0.12.11. This is working , checked and updated the code

**Comment by uriyyo** [comment]
Great, then I am closing this issue. Please, reopen it in case of any issues.
