### ISSUE TITLE
Upgrade to Pydantic 2.0

### ISSUE THREAD

**Issue by markmiscavage** [uriyyo/fastapi-pagination#853]
Pydantic has released v2.0 which has significant performance increases.

**Comment by uriyyo** [comment]
Hi @markmiscavage,

`fastapi-pagination` supports pydantic `v2` since version [0.12.6](https://github.com/uriyyo/fastapi-pagination/releases/tag/0.12.6)

**Comment by markmiscavage** [comment]
I was getting conflicts while trying to use fastapi-pagination with Pydantic v2 installed in my project. Correct me if I'm wrong but it looks like the poetry.lock file in main is still showing pydantic 1.10.8 being installed https://github.com/uriyyo/fastapi-pagination/blob/main/poetry.lock#L1424.

**Comment by uriyyo** [comment]
`pydantic` 1.10.8 is a min-supported version, but `fastapi-pagination` supports both v1 and v2 versions. You should be able to use  `pydantic` v2 without any issues.

**Comment by ningen1** [comment]
no issues on my side
fastapi              0.103.2
fastapi-pagination   0.12.10
pydantic             2.4.2
pydantic_core        2.10.1
pydantic-extra-types 2.1.0
pydantic-settings    2.0.3
