### ISSUE TITLE
sort argument (multiple fields) for motor paginate

### ISSUE THREAD

**Issue by ildarworld** [uriyyo/fastapi-pagination#871]
```
motor = "^3.3.1"
fastapi-pagination = "^0.12.9"
```

The paginate function unpacks the sort argument, which can lead to errors when sorting by multiple fields with Motor. Motor expects a list of tuples for sorting (if it is not a single field sorting), but when the sort argument is unpacked, it loses the structure and raises an error.
```python
    if sort is not None:
        cursor = cursor.sort(*sort)
```

e.g.:

```python

from fastapi_pagination.ext.motor import paginate

data = await paginate(
    db.report,
    query_filter=query,
    sort=[("created_at", -1), ("modified_at", 1)],
    params=params,
    transformer=transformer,
)
```

this code will raise an error, because inside `paginate` function it will be unpacked. But for motor it is required to pass a list of tuples when you would like to sort by multiple fields, so in this case unpack is not required

**Comment by uriyyo** [comment]
@ildarworld I am planning to release the fix tomorrow. I will notify you in case of any changes.

**Comment by uriyyo** [comment]
Hi @ildarworld,

New version `0.12.11` has been released, this issue should be fixed now.
