### ISSUE TITLE
Using `Page.with_custom_options` results in Pydantic V2 warnings

### ISSUE THREAD

**Issue by Earthling7235** [uriyyo/fastapi-pagination#892]
I am following the advanced tutorial section located at https://uriyyo-fastapi-pagination.netlify.app/tutorials_advanced/custom-params/ in order to achieve something similar.

The offending line is
```python
Page = Page.with_custom_options(size=Query(50, ge=1, le=None), page=Query(1, gt=0))
```

This results in Pydantic warnings as shown here:
```text
Page = Page.with_custom_options(size=Query(50, ge=1, le=None), page=Query(1, gt=0))
File "/app/.venv/lib/python3.10/site-packages/fastapi_pagination/bases.py", line 199, in with_custom_options
   **_create_params(params_cls, kwargs),
File "/app/.venv/lib/python3.10/site-packages/fastapi_pagination/bases.py", line 113, in _create_params
   incorrect = sorted(fields.keys() - cls.__fields__.keys() - cls.__class_vars__)
File "/app/.venv/lib/python3.10/site-packages/typing_extensions.py", line 2359, in wrapper
   warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
pydantic.warnings.PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
```

I saw another issue that said that the upgrade to Pydantic V2 has happened but I am still hitting a line that is using the deprecated `__fields__` attribute.

Versions I am using:
```
pydantic: 2.4.2
pydantic_core: 2.10.1
pydantic-settings: 2.0.3
fastapi: 0.104.0
fastapi-pagination: 0.12.11
```

Is there some other method I should be using to set those params?

**Comment by uriyyo** [comment]
Hi @Earthling7235,

Thanks for reporting about this issue, I will try to fix it ASAP.

**Comment by uriyyo** [comment]
@Earthling7235 This issue should be fixed in the new version `0.12.12`. Could you please verify it?

**Comment by Earthling7235** [comment]
I have verified I am not longer getting that warning. Thank you @uriyyo !

**Comment by uriyyo** [comment]
@Earthling7235 Thanks for update!
