### ISSUE TITLE
pydantic 2.4 show error

### ISSUE THREAD

**Issue by uxhao-o** [uriyyo/fastapi-pagination#917]
pydantic 2.4 show error

{'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': <coroutine object paginate at 0x0000014A4EA46AC0>, 'url': 'https://errors.pydantic.dev/2.4/v/model_attributes_type'}

**Comment by uriyyo** [comment]
Hi, I can see that you pass `coroutine` for validation. Maybe you missed `await` when calling `paginate` function?

**Comment by uriyyo** [comment]
Hi @uxhao-o,

Any updates?

**Comment by uriyyo** [comment]
Hi @uxhao-o,

I am closing this issue, please reopen it in case of any problems.
