### ISSUE TITLE
SQLAlchemy pagination error - pydantic.error_wrappers.ValidationError

### ISSUE THREAD

**Issue by pmlynarek** [uriyyo/fastapi-pagination#92]
Hi! 👋

**version 0.7.1**

For `sqlalchemy` extension in function `fastapi_pagination.ext.sqlalchemy.paginate`, we should rather return list of dicts instead of tuples:
https://github.com/uriyyo/fastapi-pagination/blob/0.7.1/fastapi_pagination/ext/sqlalchemy.py#L23

I get the validation error there
`items = paginate_query(query, params).all()  # as is` 
`items = [item._asdict() for item in paginate_query(query, params)]  # proposal`

Thanks 🙌

**Comment by uriyyo** [comment]
Hi @pmlynarek,

Thanks for pointing this out. It will be fixed in the scope of `0.7.2` version
