### ISSUE TITLE
ImportError: cannot import name 'AsyncConnection' from 'sqlmodel.ext.asyncio.session'

### ISSUE THREAD

**Issue by espdev** [uriyyo/fastapi-pagination#930]
Hello,

[SQLModel has been updated](https://sqlmodel.tiangolo.com/release-notes/) to version 0.0.12 with support of SQLAlchemy 2.x

In this version `AsyncConnection` cannot be imported from `sqlmodel.ext.asyncio.session` module. However, `AsyncConnection` still can be imported from `sqlalchemy.ext.asyncio.session` module.

Could you please add support for new versions of SQLModel?

**Comment by uriyyo** [comment]
Hi @espdev,

Fix will be release in 1-2 days, I will ping you, when it will be released

**Comment by uriyyo** [comment]
Hi all,

New version `0.12.3` has been released. This issue should be fixed now.

**Comment by espdev** [comment]
@uriyyo Thank you!

**Comment by uriyyo** [comment]
@espdev Can I close this issue?

**Comment by espdev** [comment]
@uriyyo yes, it works fine.

**Comment by uriyyo** [comment]
Great!
