### ISSUE TITLE
How to add new key in query result before add in to paginate?

### ISSUE THREAD

**Issue by sombathoudom** [uriyyo/fastapi-pagination#942]
I'm using
from fastapi_pagination.ext.sqlalchemy import paginate

Here is my qurey ex:
q = db.query(User)
and after query end i want to add another key to q like this.
Ex:
default q has {name: 'ABC'}
I want to add {name: 'ABC', map: 'Worldwide'}
but that map is not in user table or another table

and i return paginate(q) but i got an error.

**Comment by uriyyo** [comment]
Hi @sombathoudom,
Could you please show what kind of error you receive?

**Comment by uriyyo** [comment]
@sombathoudom I guess, you can try to use `transformer` to add another key to result set before passing it to validation stage.

**Comment by uriyyo** [comment]
@sombathoudom Any updates?

**Comment by uriyyo** [comment]
@sombathoudom  I'm closing this issue. Please, reopen it in case this issue is still relevant.
