### ISSUE TITLE
SADeprecationWarning: Object <sqlalchemy.orm.query.Query object at 0x...> should not be used directly in a SQL statement context

### ISSUE THREAD

**Issue by martin-greentrax** [uriyyo/fastapi-pagination#961]
fastapi-pagination version 0.12.14

Thank you for this great plugin! :)

I'm in the process of migrating a fastapi app to pydantic 2 and sqlalchemy 2. When running my test suite I get a lot of these deprecation warnings:
```

  /home/foo/.local/share/virtualenvs/foo-cpciIMar/lib/python3.11/site-packages/fastapi_pagination/ext/sqlalchemy.py:130: 
SADeprecationWarning: Object <sqlalchemy.orm.query.Query object at 0x7f2217801b50> should not be used directly in a SQL 
statement context, such as passing to methods such as session.execute().  This usage will be disallowed in a future release.  
Please use Core select() / update() / delete() etc. with Session.execute() and other statement execution methods.
  items = _maybe_unique(conn.execute(query), unique)
```

**Comment by uriyyo** [comment]
Hi @martin-greentrax,

You can check sqlalchemy docs about migration to version 2 - https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-orm-usage

**Comment by martin-greentrax** [comment]
Thank you very much for the swift reply, @uriyyo!
Ah ok, I didn't figure that the problem would be my code as the warning didn't point to it. But I will transform it and see!
