### ISSUE TITLE
Piccolo extension not working when selecting relational parameters

### ISSUE THREAD

**Issue by Bayoslav** [uriyyo/fastapi-pagination#982]
When I run this: 
`return await paginate(Model.select().where(Model.foreignModel.something==something))`
The piccolo extension fails with a ValueError "Values is undefined".
I did a bit of debugging and this happens because `deepcopy` is used in the piccolo ORM extension - https://github.com/uriyyo/fastapi-pagination/blob/main/fastapi_pagination/ext/piccolo.py#L32 . I changed `deepcopy` to `copy` and it works, too lazy to figure out why right now but will make a PR correcting this afterwards.

EDIT: Copy does not work either, just sets every field to null in the result query.

**Comment by uriyyo** [comment]
Hi @Bayoslav,

New version `0.12.17` has been released, this issue should be fixed now.

**Comment by uriyyo** [comment]
Hi @Bayoslav,

This issue should be fixed now, please reopen this issue in case if you still have any problems with `piccolo` extension.
